package com.mcp.rag.llm.module.config;

import com.mcp.rag.llm.module.entity.Iab;
import com.mcp.rag.llm.module.service.IabCategoriesService;
import com.opencsv.CSVReader;
import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.io.Resource;
import org.springframework.core.io.ResourceLoader;
import org.springframework.stereotype.Component;

import java.io.InputStreamReader;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@Component
public class DataInitializer implements CommandLineRunner {
    
    private final IabCategoriesService iabService;
    private final VectorStore vectorStore;

    private final ResourceLoader resourceLoader;

    @Value("${dataFileName:iab.csv}")
    private String dataFileName;
    
    @Autowired
    public DataInitializer(IabCategoriesService iabService, VectorStore vectorStore, ResourceLoader resourceLoader) {
        this.iabService = iabService;
        this.vectorStore = vectorStore;
        this.resourceLoader = resourceLoader;
    }
    
    @Override
    public void run(String... args) throws Exception {
        // Check if iabs already exist to avoid duplicates
        if (iabService.getAllIabs().size() == 0) {
            //initializeSampleIabs();
            loadInitialData();
        }
    }

    private void loadInitialData(){
        // Path matches src/main/resources/data.csv

        Resource resource = resourceLoader.getResource("classpath:" + dataFileName);

        List<Iab> list = new ArrayList<>();
        try (CSVReader reader = new CSVReader(new InputStreamReader(resource.getInputStream()))) {
            List<String[]> allRows = reader.readAll();

            // Skip header and process rows
            for (int i = 1; i < allRows.size(); i++) {
                String[] row = allRows.get(i);

                // Get values by index
                Integer id = null;
                Integer parentId = null;
                String name = null;
                String tier1 = null;
                String tier2 = null;
                String tier3 = null;
                String tier4 = null;

                if(row[0].trim().length() != 0){
                    id = Integer.valueOf(row[0].trim());
                }
                if(row[1].trim().length() != 0){
                    parentId = Integer.valueOf(row[1].trim());
                }
                if(row[2].trim().length() != 0){
                    name = row[2].trim();
                }
                if(row[3].trim().length() != 0){
                    tier1 = row[3].trim();
                }
                if(row[4].trim().length() != 0){
                    tier2 = row[4].trim();
                }
                if(row[5].trim().length() != 0){
                    tier3 = row[5].trim();
                }
                if(row[6].trim().length() != 0){
                    tier4 = row[6].trim();
                }
                Iab iab = new Iab ( id, parentId, name, tier1, tier2, tier3, tier4);
                iabService.addIab(iab);
                list.add(iab);
            }
            embedAndStoreData(list);
        } catch (Exception e) {
            throw new RuntimeException("Failed to load CSV: " + e.getMessage());
        }
    }

    public String generateEmbeddingText(Iab iab) {
        // Collect tiers into a list to filter out nulls easily
        List<String> tierPath = Stream.of(iab.getTier1(), iab.getTier2(), iab.getTier3(), iab.getTier4())
                .filter(Objects::nonNull)
                .filter(t -> !t.isBlank())
                .collect(Collectors.toList());

        String path = String.join(" > ", tierPath);
        String parentInfo = (iab.getParentId() != null) ? "Under Parent ID: " + iab.getParentId() : "Root";

        // Format: Name (ID: 123, Parent: 45) Taxonomy: Tier1 > Tier2...
        return String.format("Taxonomy/IAB has name %s (ID: %s, %s) Taxonomy Hierarchy: %s",
                iab.getName(), iab.getId(), parentInfo, path);
    }

    public void embedAndStoreData(List<Iab> iabList) {
        List<Document> documents = iabList.stream().map(iab -> {
            // 1. Create the semantic text for the embedding model
            String content = generateEmbeddingText(iab);

            // 2. Store original fields as metadata for filtering later
            Map<String, Object> metadata = new HashMap<>();
            metadata.put("id", iab.getId());
            metadata.put("name", iab.getName());
            if(iab.getParentId() != null)
                metadata.put("parentId", iab.getParentId());
            if(iab.getTier1() != null)
                metadata.put("tier1", iab.getTier1());
            if(iab.getTier2() != null)
                metadata.put("tier2", iab.getTier2());
            if(iab.getTier3() != null)
                metadata.put("tier3", iab.getTier3());
            if(iab.getTier4() != null)
                metadata.put("tier4", iab.getTier4());
            // Add other tiers if needed for filtering

            return new Document(content, metadata);
        }).collect(Collectors.toList());

        vectorStore.add(documents);
        // System.out.println("Data embedded and stored in Qdrant collection.");
        // iabService.getAllIabs();
    }

    private void initializeSampleIabs() {
        try {
            // Classic Literature
            iabService.addIab(new Iab ( 150, 150, "Attractions", "Attractions", " ", " ", " " ));
            iabService.addIab(new Iab ( 151, 150, "Amusement and Theme Parks", "Attractions", "Amusement and Theme Parks", " ", " " ));
            iabService.addIab(new Iab ( 179, 150, "Bars & Restaurants", "Attractions", "Bars & Restaurants", " ", " " ));
            iabService.addIab(new Iab ( 181, 150, "Casinos & Gambling", "Attractions", "Casinos & Gambling", " ", " " ));
            iabService.addIab(new Iab ( 153, 150, "Historic Site and Landmark Tours", "Attractions", "Historic Site and Landmark Tours", " ", " " ));
            iabService.addIab(new Iab ( 154, 150, "Malls & Shopping Centers", "Attractions", "Malls & Shopping Centers", " ", " " ));
            iabService.addIab(new Iab ( 155, 150, "Museums & Galleries", "Attractions", "Museums & Galleries", " ", " " ));
            iabService.addIab(new Iab ( 158, 150, "Nightclubs", "Attractions", "Nightclubs", " ", " " ));
            iabService.addIab(new Iab ( 159, 150, "Outdoor Attractions", "Attractions", "Outdoor Activities", " ", " " ));
            iabService.addIab(new Iab ( 160, 150, "Parks", "Attractions", "Parks & Nature", " ", " " ));
            iabService.addIab(new Iab ( 177, 150, "Theater Venues", "Attractions", "Theater Venues", " ", " " ));
            iabService.addIab(new Iab ( 178, 150, "Zoos & Aquariums", "Attractions", "Zoos & Aquariums", " ", " " ));
            iabService.addIab(new Iab ( 1,  null, "Automotive", "Automotive", " ", " ", " " ));
            iabService.addIab(new Iab ( 2, 1, "Auto Body Styles", "Automotive", "Auto Body Styles", " ", " " ));
            iabService.addIab(new Iab ( 3, 2, "Commercial Trucks", "Automotive", "Auto Body Styles", "Commercial Trucks", " " ));
            iabService.addIab(new Iab ( 8, 2, "Convertible", "Automotive", "Auto Body Styles", "Convertible", " " ));
            iabService.addIab(new Iab ( 9, 2, "Coupe", "Automotive", "Auto Body Styles", "Coupe", " " ));
            iabService.addIab(new Iab ( 10, 2, "Crossover", "Automotive", "Auto Body Styles", "Crossover", " " ));
            iabService.addIab(new Iab ( 11, 2, "Hatchback", "Automotive", "Auto Body Styles", "Hatchback", " " ));
            iabService.addIab(new Iab ( 12, 2, "Microcar", "Automotive", "Auto Body Styles", "Microcar", " " ));
            iabService.addIab(new Iab ( 13, 2, "Minivan", "Automotive", "Auto Body Styles", "Minivan", " " ));
            iabService.addIab(new Iab ( 14, 2, "Off-Road Vehicles", "Automotive", "Auto Body Styles", "Off-Road Vehicles", " " ));
            iabService.addIab(new Iab ( 15, 2, "Pickup Trucks", "Automotive", "Auto Body Styles", "Pickup Trucks", " " ));
            iabService.addIab(new Iab ( 4, 2, "Sedan", "Automotive", "Auto Body Styles", "Sedan", " " ));
            iabService.addIab(new Iab ( 5, 2, "Station Wagon", "Automotive", "Auto Body Styles", "Station Wagon", " " ));
            iabService.addIab(new Iab ( 6, 2, "SUV", "Automotive", "Auto Body Styles", "SUV", " " ));
            iabService.addIab(new Iab ( 7, 2, "Van", "Automotive", "Auto Body Styles", "Van", " " ));
            iabService.addIab(new Iab ( 30, 1, "Auto Buying and Selling", "Automotive", "Auto Buying and Selling", " ", " " ));
            iabService.addIab(new Iab ( 31, 1, "Auto Insurance", "Automotive", "Auto Insurance", " ", " " ));
            iabService.addIab(new Iab ( 32, 1, "Auto Parts", "Automotive", "Auto Parts", " ", " " ));
            iabService.addIab(new Iab ( 33, 1, "Auto Recalls", "Automotive", "Auto Recalls", " ", " " ));
            iabService.addIab(new Iab ( 41, 1, "Auto Rentals", "Automotive", "Auto Rentals", " ", " " ));
            iabService.addIab(new Iab ( 34, 1, "Auto Repair", "Automotive", "Auto Repair", " ", " " ));
            iabService.addIab(new Iab ( 35, 1, "Auto Safety", "Automotive", "Auto Safety", " ", " " ));
            iabService.addIab(new Iab ( 36, 1, "Auto Shows", "Automotive", "Auto Shows", " ", " " ));
            iabService.addIab(new Iab ( 37, 1, "Auto Technology", "Automotive", "Auto Technology", " ", " " ));
            iabService.addIab(new Iab ( 38, 37, "Auto Infotainment Technologies", "Automotive", "Auto Technology", "Auto Infotainment Technologies", " " ));
            iabService.addIab(new Iab ( 39, 37, "Auto Navigation Systems", "Automotive", "Auto Technology", "Auto Navigation Systems", " " ));
            iabService.addIab(new Iab ( 40, 37, "Auto Safety Technologies", "Automotive", "Auto Technology", "Auto Safety Technologies", " " ));
            iabService.addIab(new Iab ( 16, 1, "Auto Type", "Automotive", "Auto Type", " ", " " ));
            iabService.addIab(new Iab ( 17, 16, "Budget Cars", "Automotive", "Auto Type", "Budget Cars", " " ));
            iabService.addIab(new Iab ( 18, 16, "Certified Pre-Owned Cars", "Automotive", "Auto Type", "Certified Pre-Owned Cars", " " ));
            iabService.addIab(new Iab ( 19, 16, "Classic Cars", "Automotive", "Auto Type", "Classic Cars", " " ));
            iabService.addIab(new Iab ( 20, 16, "Concept Cars", "Automotive", "Auto Type", "Concept Cars", " " ));
            iabService.addIab(new Iab ( 21, 16, "Driverless Cars", "Automotive", "Auto Type", "Driverless Cars", " " ));
            iabService.addIab(new Iab ( 22, 16, "Green Vehicles", "Automotive", "Auto Type", "Green Vehicles", " " ));
            iabService.addIab(new Iab ( 23, 16, "Luxury Cars", "Automotive", "Auto Type", "Luxury Cars", " " ));
            iabService.addIab(new Iab ( 24, 16, "Performance Cars", "Automotive", "Auto Type", "Performance Cars", " " ));
            iabService.addIab(new Iab ( 25, 1, "Car Culture", "Automotive", "Car Culture", " ", " " ));
            iabService.addIab(new Iab ( 26, 1, "Dash Cam Videos", "Automotive", "Dash Cam Videos", " ", " " ));
            iabService.addIab(new Iab ( 27, 1, "Motorcycles", "Automotive", "Motorcycles", " ", " " ));
            iabService.addIab(new Iab ( 28, 1, "Road-Side Assistance", "Automotive", "Road-Side Assistance", " ", " " ));
            iabService.addIab(new Iab ( 29, 1, "Scooters", "Automotive", "Scooters", " ", " " ));
            iabService.addIab(new Iab ( 42, null , "Books and Literature", "Books and Literature", " ", " ", " " ));
            iabService.addIab(new Iab ( 43, 42, "Art and Photography", "Books and Literature", "Art and Photography", " ", " " ));
            iabService.addIab(new Iab ( 46, 42, "Comics and Graphic Novels", "Books and Literature", "Comics and Graphic Novels", " ", " " ));
            iabService.addIab(new Iab ( 48, 42, "Fiction", "Books and Literature", "Fiction", " ", " " ));
            iabService.addIab(new Iab ( 49, 42, "Poetry", "Books and Literature", "Poetry", " ", " " ));
            iabService.addIab(new Iab ( 52,  null, "Business and Finance", "Business and Finance", " ", " ", " " ));
            iabService.addIab(new Iab ( 53, 52, "Business", "Business and Finance", "Business", " ", " " ));
            iabService.addIab(new Iab ( 54, 53, "Business Accounting & Finance", "Business and Finance", "Business", "Business Accounting & Finance", " " ));
            iabService.addIab(new Iab ( 62, 53, "Business Administration", "Business and Finance", "Business", "Business Administration", " " ));
            iabService.addIab(new Iab ( 63, 53, "Business Banking & Finance", "Business and Finance", "Business", "Business Banking & Finance", " " ));
            iabService.addIab(new Iab ( 64, 63, "Angel Investment", "Business and Finance", "Business", "Business Banking & Finance", "Angel Investment" ));
            iabService.addIab(new Iab ( 65, 63, "Bankruptcy", "Business and Finance", "Business", "Business Banking & Finance", "Bankruptcy" ));
            iabService.addIab(new Iab ( 66, 63, "Business Loans", "Business and Finance", "Business", "Business Banking & Finance", "Business Loans" ));
            iabService.addIab(new Iab ( 67, 63, "Debt Factoring & Invoice Discounting", "Business and Finance", "Business", "Business Banking & Finance", "Debt Factoring & Invoice Discounting" ));
            iabService.addIab(new Iab ( 68, 63, "Mergers and Acquisitions", "Business and Finance", "Business", "Business Banking & Finance", "Mergers and Acquisitions" ));
            iabService.addIab(new Iab ( 69, 63, "Private Equity", "Business and Finance", "Business", "Business Banking & Finance", "Private Equity" ));
            iabService.addIab(new Iab ( 70, 63, "Sale & Lease Back", "Business and Finance", "Business", "Business Banking & Finance", "Sale & Lease Back" ));
            iabService.addIab(new Iab ( 71, 63, "Venture Capital", "Business and Finance", "Business", "Business Banking & Finance", "Venture Capital" ));
            iabService.addIab(new Iab ( 72, 53, "Business I.T.", "Business and Finance", "Business", "Business I.T.", " " ));
            iabService.addIab(new Iab ( 73, 53, "Business Operations", "Business and Finance", "Business", "Business Operations", " " ));
            iabService.addIab(new Iab ( 79, 53, "Business Utilities", "Business and Finance", "Business", "Business Utilities", " " ));
            iabService.addIab(new Iab ( 74, 53, "Consumer Issues", "Business and Finance", "Business", "Consumer Issues", " " ));
            iabService.addIab(new Iab ( 75, 74, "Recalls", "Business and Finance", "Business", "Consumer Issues", "Recalls" ));
            iabService.addIab(new Iab ( 76, 53, "Executive Leadership & Management", "Business and Finance", "Business", "Executive Leadership & Management", " " ));
            iabService.addIab(new Iab ( 77, 53, "Government Business", "Business and Finance", "Business", "Government Business", " " ));
            iabService.addIab(new Iab ( 78, 53, "Green Solutions", "Business and Finance", "Business", "Green Solutions", " " ));
            iabService.addIab(new Iab ( 55, 53, "Human Resources", "Business and Finance", "Business", "Human Resources", " " ));
            iabService.addIab(new Iab ( 56, 53, "Large Business", "Business and Finance", "Business", "Large Business", " " ));
            iabService.addIab(new Iab ( 57, 53, "Logistics", "Business and Finance", "Business", "Logistics", " " ));
            iabService.addIab(new Iab ( 58, 53, "Marketing and Advertising", "Business and Finance", "Business", "Marketing and Advertising", " " ));
            iabService.addIab(new Iab ( 59, 53, "Sales", "Business and Finance", "Business", "Sales", " " ));
            iabService.addIab(new Iab ( 60, 53, "Small and Medium-sized Business", "Business and Finance", "Business", "Small and Medium-sized Business", " " ));
            iabService.addIab(new Iab ( 61, 53, "Startups", "Business and Finance", "Business", "Startups", " " ));
            iabService.addIab(new Iab ( 80, 52, "Economy", "Business and Finance", "Economy", " ", " " ));
            iabService.addIab(new Iab ( 81, 80, "Commodities", "Business and Finance", "Economy", "Commodities", " " ));
            iabService.addIab(new Iab ( 82, 80, "Currencies", "Business and Finance", "Economy", "Currencies", " " ));
            iabService.addIab(new Iab ( 83, 80, "Financial Crisis", "Business and Finance", "Economy", "Financial Crisis", " " ));
            iabService.addIab(new Iab ( 84, 80, "Financial Reform", "Business and Finance", "Economy", "Financial Reform", " " ));
            iabService.addIab(new Iab ( 85, 80, "Financial Regulation", "Business and Finance", "Economy", "Financial Regulation", " " ));
            iabService.addIab(new Iab ( 86, 80, "Gasoline Prices", "Business and Finance", "Economy", "Gasoline Prices", " " ));
            iabService.addIab(new Iab ( 87, 80, "Housing Market", "Business and Finance", "Economy", "Housing Market", " " ));
            iabService.addIab(new Iab ( 88, 80, "Interest Rates", "Business and Finance", "Economy", "Interest Rates", " " ));
            iabService.addIab(new Iab ( 89, 80, "Job Market", "Business and Finance", "Economy", "Job Market", " " ));
            iabService.addIab(new Iab ( 90, 52, "Industries", "Business and Finance", "Industries", " ", " " ));
            iabService.addIab(new Iab ( 91, 90, "Advertising Industry", "Business and Finance", "Industries", "Advertising Industry", " " ));
            iabService.addIab(new Iab ( 102, 90, "Agriculture", "Business and Finance", "Industries", "Agriculture", " " ));
            iabService.addIab(new Iab ( 113, 90, "Apparel Industry", "Business and Finance", "Industries", "Apparel Industry", " " ));
            iabService.addIab(new Iab ( 117, 90, "Automotive Industry", "Business and Finance", "Industries", "Automotive Industry", " " ));
            iabService.addIab(new Iab ( 118, 90, "Aviation Industry", "Business and Finance", "Industries", "Aviation Industry", " " ));
            iabService.addIab(new Iab ( 119, 90, "Biotech and Biomedical Industry", "Business and Finance", "Industries", "Biotech and Biomedical Industry", " " ));
            iabService.addIab(new Iab ( 120, 90, "Civil Engineering Industry", "Business and Finance", "Industries", "Civil Engineering Industry", " " ));
            iabService.addIab(new Iab ( 121, 90, "Construction Industry", "Business and Finance", "Industries", "Construction Industry", " " ));
            iabService.addIab(new Iab ( 122, 90, "Defense Industry", "Business and Finance", "Industries", "Defense Industry", " " ));
            iabService.addIab(new Iab ( 92, 90, "Education industry", "Business and Finance", "Industries", "Education industry", " " ));
            iabService.addIab(new Iab ( 93, 90, "Entertainment Industry", "Business and Finance", "Industries", "Entertainment Industry", " " ));
            iabService.addIab(new Iab ( 94, 90, "Environmental Services Industry", "Business and Finance", "Industries", "Environmental Services Industry", " " ));
            iabService.addIab(new Iab ( 95, 90, "Financial Industry", "Business and Finance", "Industries", "Financial Industry", " " ));
            iabService.addIab(new Iab ( 96, 90, "Food Industry", "Business and Finance", "Industries", "Food Industry", " " ));
            iabService.addIab(new Iab ( 97, 90, "Healthcare Industry", "Business and Finance", "Industries", "Healthcare Industry", " " ));
            iabService.addIab(new Iab ( 98, 90, "Hospitality Industry", "Business and Finance", "Industries", "Hospitality Industry", " " ));
            iabService.addIab(new Iab ( 99, 90, "Information Services Industry", "Business and Finance", "Industries", "Information Services Industry", " " ));
            iabService.addIab(new Iab ( 100, 90, "Legal Services Industry", "Business and Finance", "Industries", "Legal Services Industry", " " ));
            iabService.addIab(new Iab ( 101, 90, "Logistics and Transportation Industry", "Business and Finance", "Industries", "Logistics and Transportation Industry", " " ));
            iabService.addIab(new Iab ( 103, 90, "Management Consulting Industry", "Business and Finance", "Industries", "Management Consulting Industry", " " ));
            iabService.addIab(new Iab ( 104, 90, "Manufacturing Industry", "Business and Finance", "Industries", "Manufacturing Industry", " " ));
            iabService.addIab(new Iab ( 105, 90, "Mechanical and Industrial Engineering Industry", "Business and Finance", "Industries", "Mechanical and Industrial Engineering Industry", " " ));
            iabService.addIab(new Iab ( 106, 90, "Media Industry", "Business and Finance", "Industries", "Media Industry", " " ));
            iabService.addIab(new Iab ( 107, 90, "Metals Industry", "Business and Finance", "Industries", "Metals Industry", " " ));
            iabService.addIab(new Iab ( 108, 90, "Non-Profit Organizations", "Business and Finance", "Industries", "Non-Profit Organizations", " " ));
            iabService.addIab(new Iab ( 109, 90, "Pharmaceutical Industry", "Business and Finance", "Industries", "Pharmaceutical Industry", " " ));
            iabService.addIab(new Iab ( 110, 90, "Power and Energy Industry", "Business and Finance", "Industries", "Power and Energy Industry", " " ));
            iabService.addIab(new Iab ( 111, 90, "Publishing Industry", "Business and Finance", "Industries", "Publishing Industry", " " ));
            iabService.addIab(new Iab ( 112, 90, "Real Estate Industry", "Business and Finance", "Industries", "Real Estate Industry", " " ));
            iabService.addIab(new Iab ( 114, 90, "Retail Industry", "Business and Finance", "Industries", "Retail Industry", " " ));
            iabService.addIab(new Iab ( 115, 90, "Technology Industry", "Business and Finance", "Industries", "Technology Industry", " " ));
            iabService.addIab(new Iab ( 116, 90, "Telecommunications Industry", "Business and Finance", "Industries", "Telecommunications Industry", " " ));
            iabService.addIab(new Iab ( 123, null, "Careers", "Careers", " ", " ", " " ));
            iabService.addIab(new Iab ( 124, 123, "Apprenticeships", "Careers", "Apprenticeships", " ", " " ));
            iabService.addIab(new Iab ( 125, 123, "Career Advice", "Careers", "Career Advice", " ", " " ));
            iabService.addIab(new Iab ( 126, 123, "Career Planning", "Careers", "Career Planning", " ", " " ));
            iabService.addIab(new Iab ( 127, 123, "Job Search", "Careers", "Job Search", " ", " " ));
            iabService.addIab(new Iab ( 128, 127, "Job Fairs", "Careers", "Job Search", "Job Fairs", " " ));
            iabService.addIab(new Iab ( 129, 127, "Resume Writing and Advice", "Careers", "Job Search", "Resume Writing and Advice", " " ));
            iabService.addIab(new Iab ( 130, 123, "Remote Working", "Careers", "Remote Working", " ", " " ));
            iabService.addIab(new Iab ( 131, 123, "Vocational Training", "Careers", "Vocational Training", " ", " " ));
            iabService.addIab(new Iab ( 10001, null, "Communication", "Communication", " ", " ", " " ));
            iabService.addIab(new Iab ( 380, null, "Crime", "Crime", " ", " ", " " ));
            iabService.addIab(new Iab ( 381, null, "Disasters", "Disasters", " ", " ", " " ));
            iabService.addIab(new Iab ( 132, null, "Education", "Education", " ", " ", " " ));
            iabService.addIab(new Iab ( 133, 132, "Adult Education", "Education", "Adult Education", " ", " " ));
            iabService.addIab(new Iab ( 137, 132, "College Education", "Education", "College Education", " ", " " ));
            iabService.addIab(new Iab ( 138, 137, "College Planning", "Education", "College Education", "College Planning", " " ));
            iabService.addIab(new Iab ( 139, 137, "Postgraduate Education", "Education", "College Education", "Postgraduate Education", " " ));
            iabService.addIab(new Iab ( 140, 139, "Professional School", "Education", "College Education", "Postgraduate Education", "Professional School" ));
            iabService.addIab(new Iab ( 141, 137, "Undergraduate Education", "Education", "College Education", "Undergraduate Education", " " ));
            iabService.addIab(new Iab ( 142, 132, "Early Childhood Education", "Education", "Early Childhood Education", " ", " " ));
            iabService.addIab(new Iab ( 143, 132, "Educational Assessment", "Education", "Educational Assessment", " ", " " ));
            iabService.addIab(new Iab ( 144, 143, "Standardized Testing", "Education", "Educational Assessment", "Standardized Testing", " " ));
            iabService.addIab(new Iab ( 145, 132, "Homeschooling", "Education", "Homeschooling", " ", " " ));
            iabService.addIab(new Iab ( 146, 132, "Homework and Study", "Education", "Homework and Study", " ", " " ));
            iabService.addIab(new Iab ( 147, 132, "Language Learning", "Education", "Language Learning", " ", " " ));
            iabService.addIab(new Iab ( 148, 132, "Online Education", "Education", "Online Education", " ", " " ));
            iabService.addIab(new Iab ( 149, 132, "Primary Education", "Education", "Primary Education", " ", " " ));
            iabService.addIab(new Iab ( 134, 132, "Private School", "Education", "Private School", " ", " " ));
            iabService.addIab(new Iab ( 135, 132, "Secondary Education", "Education", "Secondary Education", " ", " " ));
            iabService.addIab(new Iab ( 136, 132, "Special Education", "Education", "Special Education", " ", " " ));
            iabService.addIab(new Iab ( 10002, null, "Entertainment", "Entertainment", " ", " ", " " ));
            iabService.addIab(new Iab ( 324, 10002, "Movies", "Entertainment", "Movies", " ", " " ));
            iabService.addIab(new Iab ( 338, 10002, "Music", "Entertainment", "Music", " ", " " ));
            iabService.addIab(new Iab ( 640, 10002, "Television", "Entertainment", "Television", " ", " " ));
            iabService.addIab(new Iab ( 10003, null, "Events", "Events", " ", " ", " " ));
            iabService.addIab(new Iab ( 162, 10003, "Awards Shows", "Events", "Awards Shows", " ", " " ));
            iabService.addIab(new Iab ( 180, 10003, "Business Expos & Conferences", "Events", "Business Expos & Conferences", " ", " " ));
            iabService.addIab(new Iab ( 185, 10003, "Fan Conventions", "Events", "Fan Conventions", " ", " " ));
            iabService.addIab(new Iab ( 186, 186, "Family and Relationships", "Family and Relationships", " ", " ", " " ));
            iabService.addIab(new Iab ( 187, 186, "Bereavement", "Family and Relationships", "Bereavement", " ", " " ));
            iabService.addIab(new Iab ( 188, 186, "Dating", "Family and Relationships", "Dating", " ", " " ));
            iabService.addIab(new Iab ( 189, 186, "Divorce", "Family and Relationships", "Divorce", " ", " " ));
            iabService.addIab(new Iab ( 190, 186, "Eldercare", "Family and Relationships", "Eldercare", " ", " " ));
            iabService.addIab(new Iab ( 191, 186, "Marriage and Civil Unions", "Family and Relationships", "Marriage and Civil Unions", " ", " " ));
            iabService.addIab(new Iab ( 192, 186, "Parenting", "Family and Relationships", "Parenting", " ", " " ));
            iabService.addIab(new Iab ( 193, 192, "Adoption and Fostering", "Family and Relationships", "Parenting", "Adoption and Fostering", " " ));
            iabService.addIab(new Iab ( 194, 192, "Daycare and Pre-School", "Family and Relationships", "Parenting", "Daycare and Pre-School", " " ));
            iabService.addIab(new Iab ( 195, 192, "Internet Safety", "Family and Relationships", "Parenting", "Internet Safety", " " ));
            iabService.addIab(new Iab ( 196, 192, "Parenting Babies and Toddlers", "Family and Relationships", "Parenting", "Parenting Babies and Toddlers", " " ));
            iabService.addIab(new Iab ( 197, 192, "Parenting Children Aged 4-11", "Family and Relationships", "Parenting", "Parenting Children Aged 4-11", " " ));
            iabService.addIab(new Iab ( 198, 192, "Parenting Teens", "Family and Relationships", "Parenting", "Parenting Teens", " " ));
            iabService.addIab(new Iab ( 199, 192, "Special Needs Kids", "Family and Relationships", "Parenting", "Special Needs Kids", " " ));
            iabService.addIab(new Iab ( 200, 186, "Single Life", "Family and Relationships", "Single Life", " ", " " ));
            iabService.addIab(new Iab ( 201, null, "Fine Art", "Fine Art", " ", " ", " " ));
            iabService.addIab(new Iab ( 202, 201, "Costume", "Fine Art", "Costume", " ", " " ));
            iabService.addIab(new Iab ( 203, 201, "Dance", "Fine Art", "Dance", " ", " " ));
            iabService.addIab(new Iab ( 204, 201, "Design", "Fine Art", "Design", " ", " " ));
            iabService.addIab(new Iab ( 205, 201, "Digital Arts", "Fine Art", "Digital Arts", " ", " " ));
            iabService.addIab(new Iab ( 206, 201, "Fine Art Photography", "Fine Art", "Fine Art Photography", " ", " " ));
            iabService.addIab(new Iab ( 207, 201, "Modern Art", "Fine Art", "Modern Art", " ", " " ));
            iabService.addIab(new Iab ( 208, 201, "Opera", "Fine Art", "Opera", " ", " " ));
            iabService.addIab(new Iab ( 209, 201, "Theater", "Fine Art", "Theater", " ", " " ));
            iabService.addIab(new Iab ( 210, null, "Food & Drink", "Food & Drink", " ", " ", " " ));
            iabService.addIab(new Iab ( 211, 210, "Alcoholic Beverages", "Food & Drink", "Alcoholic Beverages", " ", " " ));
            iabService.addIab(new Iab ( 215, 210, "Barbecues and Grilling", "Food & Drink", "Barbecues and Grilling", " ", " " ));
            iabService.addIab(new Iab ( 216, 210, "Cooking", "Food & Drink", "Cooking", " ", " " ));
            iabService.addIab(new Iab ( 217, 210, "Desserts and Baking", "Food & Drink", "Desserts and Baking", " ", " " ));
            iabService.addIab(new Iab ( 218, 210, "Dining Out", "Food & Drink", "Dining Out", " ", " " ));
            iabService.addIab(new Iab ( 219, 210, "Food Allergies", "Food & Drink", "Food Allergies", " ", " " ));
            iabService.addIab(new Iab ( 220, 210, "Food Movements", "Food & Drink", "Food Movements", " ", " " ));
            iabService.addIab(new Iab ( 221, 210, "Healthy Cooking and Eating", "Food & Drink", "Healthy Cooking and Eating", " ", " " ));
            iabService.addIab(new Iab ( 222, 210, "Non-Alcoholic Beverages", "Food & Drink", "Non-Alcoholic Beverages", " ", " " ));
            iabService.addIab(new Iab ( 212, 210, "Vegan Diets", "Food & Drink", "Vegan Diets", " ", " " ));
            iabService.addIab(new Iab ( 213, 210, "Vegetarian Diets", "Food & Drink", "Vegetarian Diets", " ", " " ));
            iabService.addIab(new Iab ( 214, 210, "World Cuisines", "Food & Drink", "World Cuisines", " ", " " ));
            iabService.addIab(new Iab ( 10004, null, "Genres", "Genres", " ", " ", " " ));
            iabService.addIab(new Iab ( 10005, 10004, "Nature", "Genres", " ", " ", " " ));
            iabService.addIab(new Iab ( 325, 10004, "Action/Adventure", "Genres", "Action/Adventure", " ", " " ));
            iabService.addIab(new Iab ( 641, 10004, "Animation & Anime", "Genres", "Animation & Anime", " ", " " ));
            iabService.addIab(new Iab ( 44, 10004, "Biographies", "Genres", "Biographies", " ", " " ));
            iabService.addIab(new Iab ( 646, 10004, "Comedy", "Genres", "Comedy", " ", " " ));
            iabService.addIab(new Iab ( 332, 10004, "Documentary", "Genres", "Documentary", " ", " " ));
            iabService.addIab(new Iab ( 647, 10004, "Drama", "Genres", "Drama", " ", " " ));
            iabService.addIab(new Iab ( 648, 10004, "Factual", "Genres", "Factual", " ", " " ));
            iabService.addIab(new Iab ( 645, 10004, "Family/Children", "Genres", "Family/Children", " ", " " ));
            iabService.addIab(new Iab ( 335, 10004, "Fantasy", "Genres", "Fantasy", " ", " " ));
            iabService.addIab(new Iab ( 10006, 10004, "History", "Genres", "History", " ", " " ));
            iabService.addIab(new Iab ( 649, 10004, "Holiday", "Genres", "Holiday", " ", " " ));
            iabService.addIab(new Iab ( 336, 10004, "Horror", "Genres", "Horror", " ", " " ));
            iabService.addIab(new Iab ( 10007, 10004, "Lifestyle", "Genres", "Lifestyle", " ", " " ));
            iabService.addIab(new Iab ( 650, 10004, "Music Video", "Genres", "Music Video", " ", " " ));
            iabService.addIab(new Iab ( 156, 10004, "Musicals", "Genres", "Musical", " ", " " ));
            iabService.addIab(new Iab ( 331, 10004, "Mystery", "Genres", "Mystery", " ", " " ));
            iabService.addIab(new Iab ( 651, 10004, "Reality TV", "Genres", "Reality TV", " ", " " ));
            iabService.addIab(new Iab ( 326, 10004, "Romance", "Genres", "Romance", " ", " " ));
            iabService.addIab(new Iab ( 652, 10004, "Science Fiction", "Genres", "Science Fiction", " ", " " ));
            iabService.addIab(new Iab ( 642, 10004, "Soap Opera", "Genres", "Soap Opera", " ", " " ));
            iabService.addIab(new Iab ( 643, 10004, "Special Interest (Indie/Art House)", "Genres", "Special Interest (Indie/Art House)", " ", " " ));
            iabService.addIab(new Iab ( 370, 10004, "Sports Radio", "Genres", "Sports Radio", " ", " " ));
            iabService.addIab(new Iab ( 371, 10004, "Talk Radio", "Genres", "Talk Radio", " ", " " ));
            iabService.addIab(new Iab ( 376, 10004, "Public Radio", "Genres", "Talk Radio", "Public Radio", " " ));
            iabService.addIab(new Iab ( 10008, 10004, "Talk Show", "Genres", "Talk Show", " ", " " ));
            iabService.addIab(new Iab ( 10009, 10004, "True Crime", "Genres", "True Crime", " ", " " ));
            iabService.addIab(new Iab ( 10010, 10004, "Western", "Genres", "Western", " ", " " ));
            iabService.addIab(new Iab ( 51, 10004, "Young Adult", "Genres", "Young Adult ", " ", " " ));
            iabService.addIab(new Iab ( 223, null, "Healthy Living", "Healthy Living", " ", " ", " " ));
            iabService.addIab(new Iab ( 224, 223, "Children's Health", "Healthy Living", "Children's Health", " ", " " ));
            iabService.addIab(new Iab ( 225, 223, "Fitness and Exercise", "Healthy Living", "Fitness and Exercise", " ", " " ));
            iabService.addIab(new Iab ( 226, 225, "Participant Sports", "Healthy Living", "Fitness and Exercise", "Participant Sports", " " ));
            iabService.addIab(new Iab ( 227, 225, "Running and Jogging", "Healthy Living", "Fitness and Exercise", "Running and Jogging", " " ));
            iabService.addIab(new Iab ( 228, 223, "Men's Health", "Healthy Living", "Men's Health", " ", " " ));
            iabService.addIab(new Iab ( 229, 223, "Nutrition", "Healthy Living", "Nutrition", " ", " " ));
            iabService.addIab(new Iab ( 230, 223, "Senior Health", "Healthy Living", "Senior Health", " ", " " ));
            iabService.addIab(new Iab ( 231, 223, "Weight Loss", "Healthy Living", "Weight Loss", " ", " " ));
            iabService.addIab(new Iab ( 232, 223, "Wellness", "Healthy Living", "Wellness", " ", " " ));
            iabService.addIab(new Iab ( 233, 232, "Alternative Medicine", "Healthy Living", "Wellness", "Alternative Medicine", " " ));
            iabService.addIab(new Iab ( 234, 233, "Herbs and Supplements", "Healthy Living", "Wellness", "Alternative Medicine", "Herbs and Supplements" ));
            iabService.addIab(new Iab ( 235, 233, "Holistic Health", "Healthy Living", "Wellness", "Alternative Medicine", "Holistic Health" ));
            iabService.addIab(new Iab ( 236, 232, "Physical Therapy", "Healthy Living", "Wellness", "Physical Therapy", " " ));
            iabService.addIab(new Iab ( 237, 232, "Smoking Cessation", "Healthy Living", "Wellness", "Smoking Cessation", " " ));
            iabService.addIab(new Iab ( 238, 223, "Women's Health", "Healthy Living", "Women's Health", " ", " " ));
            iabService.addIab(new Iab ( 239, null, "Hobbies & Interests", "Hobbies & Interests", " ", " ", " " ));
            iabService.addIab(new Iab ( 240, 239, "Antiquing and Antiques", "Hobbies & Interests", "Antiquing and Antiques", " ", " " ));
            iabService.addIab(new Iab ( 248, 239, "Arts and Crafts", "Hobbies & Interests", "Arts and Crafts", " ", " " ));
            iabService.addIab(new Iab ( 249, 248, "Beadwork", "Hobbies & Interests", "Arts and Crafts", "Beadwork", " " ));
            iabService.addIab(new Iab ( 250, 248, "Candle and Soap Making", "Hobbies & Interests", "Arts and Crafts", "Candle and Soap Making", " " ));
            iabService.addIab(new Iab ( 251, 248, "Drawing and Sketching", "Hobbies & Interests", "Arts and Crafts", "Drawing and Sketching", " " ));
            iabService.addIab(new Iab ( 252, 248, "Jewelry Making", "Hobbies & Interests", "Arts and Crafts", "Jewelry Making", " " ));
            iabService.addIab(new Iab ( 253, 248, "Needlework", "Hobbies & Interests", "Arts and Crafts", "Needlework", " " ));
            iabService.addIab(new Iab ( 254, 248, "Painting", "Hobbies & Interests", "Arts and Crafts", "Painting", " " ));
            iabService.addIab(new Iab ( 255, 248, "Photography", "Hobbies & Interests", "Arts and Crafts", "Photography", " " ));
            iabService.addIab(new Iab ( 256, 248, "Scrapbooking", "Hobbies & Interests", "Arts and Crafts", "Scrapbooking", " " ));
            iabService.addIab(new Iab ( 257, 248, "Woodworking", "Hobbies & Interests", "Arts and Crafts", "Woodworking", " " ));
            iabService.addIab(new Iab ( 258, 239, "Beekeeping", "Hobbies & Interests", "Beekeeping", " ", " " ));
            iabService.addIab(new Iab ( 259, 239, "Birdwatching", "Hobbies & Interests", "Birdwatching", " ", " " ));
            iabService.addIab(new Iab ( 260, 239, "Cigars", "Hobbies & Interests", "Cigars", " ", " " ));
            iabService.addIab(new Iab ( 261, 239, "Collecting", "Hobbies & Interests", "Collecting", " ", " " ));
            iabService.addIab(new Iab ( 262, 261, "Comic Books", "Hobbies & Interests", "Collecting", "Comic Books", " " ));
            iabService.addIab(new Iab ( 263, 261, "Stamps and Coins", "Hobbies & Interests", "Collecting", "Stamps and Coins", " " ));
            iabService.addIab(new Iab ( 264, 239, "Content Production", "Hobbies & Interests", "Content Production", " ", " " ));
            iabService.addIab(new Iab ( 265, 264, "Audio Production", "Hobbies & Interests", "Content Production", "Audio Production", " " ));
            iabService.addIab(new Iab ( 266, 264, "Freelance Writing", "Hobbies & Interests", "Content Production", "Freelance Writing", " " ));
            iabService.addIab(new Iab ( 267, 264, "Screenwriting", "Hobbies & Interests", "Content Production", "Screenwriting", " " ));
            iabService.addIab(new Iab ( 268, 264, "Video Production", "Hobbies & Interests", "Content Production", "Video Production", " " ));
            iabService.addIab(new Iab ( 269, 239, "Games and Puzzles", "Hobbies & Interests", "Games and Puzzles", " ", " " ));
            iabService.addIab(new Iab ( 270, 269, "Board Games and Puzzles", "Hobbies & Interests", "Games and Puzzles", "Board Games and Puzzles", " " ));
            iabService.addIab(new Iab ( 271, 269, "Card Games", "Hobbies & Interests", "Games and Puzzles", "Card Games", " " ));
            iabService.addIab(new Iab ( 272, 269, "Roleplaying Games", "Hobbies & Interests", "Games and Puzzles", "Roleplaying Games", " " ));
            iabService.addIab(new Iab ( 273, 239, "Genealogy and Ancestry", "Hobbies & Interests", "Genealogy and Ancestry", " ", " " ));
            iabService.addIab(new Iab ( 241, 239, "Magic and Illusion", "Hobbies & Interests", "Magic and Illusion", " ", " " ));
            iabService.addIab(new Iab ( 242, 239, "Model Toys", "Hobbies & Interests", "Model Toys", " ", " " ));
            iabService.addIab(new Iab ( 243, 239, "Musical Instruments", "Hobbies & Interests", "Musical Instruments", " ", " " ));
            iabService.addIab(new Iab ( 244, 239, "Paranormal Phenomena", "Hobbies & Interests", "Paranormal Phenomena", " ", " " ));
            iabService.addIab(new Iab ( 245, 239, "Radio Control", "Hobbies & Interests", "Radio Control", " ", " " ));
            iabService.addIab(new Iab ( 246, 239, "Sci-fi and Fantasy", "Hobbies & Interests", "Sci-fi and Fantasy", " ", " " ));
            iabService.addIab(new Iab ( 247, 239, "Workshops and Classes", "Hobbies & Interests", "Workshops and Classes", " ", " " ));
            iabService.addIab(new Iab ( 10011, null, "Holidays", "Holidays", " ", " ", " " ));
            iabService.addIab(new Iab ( 157, 10011, "National & Civic Holidays", "Holidays", "National & Civic Holidays", " ", " " ));
            iabService.addIab(new Iab ( 274, null, "Home & Garden", "Home & Garden", " ", " ", " " ));
            iabService.addIab(new Iab ( 275, 274, "Gardening", "Home & Garden", "Gardening", " ", " " ));
            iabService.addIab(new Iab ( 278, 274, "Home Appliances", "Home & Garden", "Home Appliances", " ", " " ));
            iabService.addIab(new Iab ( 279, 274, "Home Entertaining", "Home & Garden", "Home Entertaining", " ", " " ));
            iabService.addIab(new Iab ( 280, 274, "Home Improvement", "Home & Garden", "Home Improvement", " ", " " ));
            iabService.addIab(new Iab ( 281, 274, "Home Security", "Home & Garden", "Home Security", " ", " " ));
            iabService.addIab(new Iab ( 282, 274, "Indoor Environmental Quality", "Home & Garden", "Indoor Environmental Quality", " ", " " ));
            iabService.addIab(new Iab ( 283, 274, "Interior Decorating", "Home & Garden", "Interior Decorating", " ", " " ));
            iabService.addIab(new Iab ( 284, 274, "Landscaping", "Home & Garden", "Landscaping", " ", " " ));
            iabService.addIab(new Iab ( 285, 274, "Outdoor Decorating", "Home & Garden", "Outdoor Decorating", " ", " " ));
            iabService.addIab(new Iab ( 276, 274, "Remodeling & Construction", "Home & Garden", "Remodeling & Construction", " ", " " ));
            iabService.addIab(new Iab ( 277, 274, "Smart Home", "Home & Garden", "Smart Home", " ", " " ));
            iabService.addIab(new Iab ( 383, null, "Law", "Law", " ", " ", " " ));
            iabService.addIab(new Iab ( 10012, 602, "Maps & Navigation", "Maps & Navigation", " ", " ", " " ));
            iabService.addIab(new Iab ( 286, null, "Medical Health", "Medical Health", " ", " ", " " ));
            iabService.addIab(new Iab ( 323, 286, "Cosmetic Medical Services", "Medical Health", "Cosmetic Medical Services", " ", " " ));
            iabService.addIab(new Iab ( 287, 286, "Diseases and Conditions", "Medical Health", "Diseases and Conditions", " ", " " ));
            iabService.addIab(new Iab ( 288, 287, "Allergies", "Medical Health", "Diseases and Conditions", "Allergies", " " ));
            iabService.addIab(new Iab ( 306, 287, "Blood Disorders", "Medical Health", "Diseases and Conditions", "Blood Disorders", " " ));
            iabService.addIab(new Iab ( 312, 287, "Bone and Joint Conditions", "Medical Health", "Diseases and Conditions", "Bone and Joint Conditions", " " ));
            iabService.addIab(new Iab ( 313, 287, "Brain and Nervous System Disorders", "Medical Health", "Diseases and Conditions", "Brain and Nervous System Disorders", " " ));
            iabService.addIab(new Iab ( 314, 287, "Cancer", "Medical Health", "Diseases and Conditions", "Cancer", " " ));
            iabService.addIab(new Iab ( 315, 287, "Cold and Flu", "Medical Health", "Diseases and Conditions", "Cold and Flu", " " ));
            iabService.addIab(new Iab ( 316, 287, "Dental Health", "Medical Health", "Diseases and Conditions", "Dental Health", " " ));
            iabService.addIab(new Iab ( 317, 287, "Diabetes", "Medical Health", "Diseases and Conditions", "Diabetes", " " ));
            iabService.addIab(new Iab ( 318, 287, "Digestive Disorders", "Medical Health", "Diseases and Conditions", "Digestive Disorders", " " ));
            iabService.addIab(new Iab ( 289, 287, "Ear, Nose and Throat Conditions", "Medical Health", "Diseases and Conditions", "Ear, Nose and Throat Conditions", " " ));
            iabService.addIab(new Iab ( 290, 287, "Endocrine and Metabolic Diseases", "Medical Health", "Diseases and Conditions", "Endocrine and Metabolic Diseases", " " ));
            iabService.addIab(new Iab ( 291, 290, "Hormonal Disorders", "Medical Health", "Diseases and Conditions", "Endocrine and Metabolic Diseases", "Hormonal Disorders" ));
            iabService.addIab(new Iab ( 292, 290, "Menopause", "Medical Health", "Diseases and Conditions", "Endocrine and Metabolic Diseases", "Menopause" ));
            iabService.addIab(new Iab ( 293, 290, "Thyroid Disorders", "Medical Health", "Diseases and Conditions", "Endocrine and Metabolic Diseases", "Thyroid Disorders" ));
            iabService.addIab(new Iab ( 294, 287, "Eye and Vision Conditions", "Medical Health", "Diseases and Conditions", "Eye and Vision Conditions", " " ));
            iabService.addIab(new Iab ( 295, 287, "Foot Health", "Medical Health", "Diseases and Conditions", "Foot Health", " " ));
            iabService.addIab(new Iab ( 296, 287, "Heart and Cardiovascular Diseases", "Medical Health", "Diseases and Conditions", "Heart and Cardiovascular Diseases", " " ));
            iabService.addIab(new Iab ( 297, 287, "Infectious Diseases", "Medical Health", "Diseases and Conditions", "Infectious Diseases", " " ));
            iabService.addIab(new Iab ( 298, 287, "Injuries", "Medical Health", "Diseases and Conditions", "Injuries", " " ));
            iabService.addIab(new Iab ( 299, 298, "First Aid", "Medical Health", "Diseases and Conditions", "Injuries", "First Aid" ));
            iabService.addIab(new Iab ( 300, 287, "Lung and Respiratory Health", "Medical Health", "Diseases and Conditions", "Lung and Respiratory Health", " " ));
            iabService.addIab(new Iab ( 301, 287, "Mental Health", "Medical Health", "Diseases and Conditions", "Mental Health", " " ));
            iabService.addIab(new Iab ( 302, 287, "Reproductive Health", "Medical Health", "Diseases and Conditions", "Reproductive Health", " " ));
            iabService.addIab(new Iab ( 303, 302, "Birth Control", "Medical Health", "Diseases and Conditions", "Reproductive Health", "Birth Control" ));
            iabService.addIab(new Iab ( 304, 302, "Infertility", "Medical Health", "Diseases and Conditions", "Reproductive Health", "Infertility" ));
            iabService.addIab(new Iab ( 305, 302, "Pregnancy", "Medical Health", "Diseases and Conditions", "Reproductive Health", "Pregnancy" ));
            iabService.addIab(new Iab ( 307, 287, "Sexual Health", "Medical Health", "Diseases and Conditions", "Sexual Health", " " ));
            iabService.addIab(new Iab ( 308, 307, "Sexual Conditions", "Medical Health", "Diseases and Conditions", "Sexual Health", "Sexual Conditions" ));
            iabService.addIab(new Iab ( 309, 287, "Skin and Dermatology", "Medical Health", "Diseases and Conditions", "Skin and Dermatology", " " ));
            iabService.addIab(new Iab ( 310, 287, "Sleep Disorders", "Medical Health", "Diseases and Conditions", "Sleep Disorders", " " ));
            iabService.addIab(new Iab ( 311, 287, "Substance Abuse", "Medical Health", "Diseases and Conditions", "Substance Abuse", " " ));
            iabService.addIab(new Iab ( 319, 286, "Medical Tests", "Medical Health", "Medical Tests", " ", " " ));
            iabService.addIab(new Iab ( 320, 286, "Pharmaceutical Drugs", "Medical Health", "Pharmaceutical Drugs", " ", " " ));
            iabService.addIab(new Iab ( 321, 286, "Surgery", "Medical Health", "Surgery", " ", " " ));
            iabService.addIab(new Iab ( 322, 286, "Vaccines", "Medical Health", "Vaccines", " ", " " ));
            iabService.addIab(new Iab ( 342, 338, "Adult Album Alternative", "Music", "Adult Album Alternative", " ", " " ));
            iabService.addIab(new Iab ( 339, 338, "Adult Contemporary Music", "Music", "Adult Contemporary Music", " ", " " ));
            iabService.addIab(new Iab ( 340, 339, "Soft AC Music", "Music", "Adult Contemporary Music", "Soft AC Music", " " ));
            iabService.addIab(new Iab ( 341, 339, "Urban AC Music", "Music", "Adult Contemporary Music", "Urban AC Music", " " ));
            iabService.addIab(new Iab ( 343, 338, "Alternative Music", "Music", "Alternative Music", " ", " " ));
            iabService.addIab(new Iab ( 360, 338, "Blues", "Music", "Blues", " ", " " ));
            iabService.addIab(new Iab ( 344, 338, "Children's Music", "Music", "Children's Music", " ", " " ));
            iabService.addIab(new Iab ( 345, 338, "Classic Hits", "Music", "Classic Hits", " ", " " ));
            iabService.addIab(new Iab ( 346, 338, "Classical Music", "Music", "Classical Music", " ", " " ));
            iabService.addIab(new Iab ( 347, 338, "College Radio", "Music", "College Radio", " ", " " ));
            iabService.addIab(new Iab ( 348, 338, "Comedy (Music and Audio)", "Music", "Comedy (Music and Audio)", " ", " " ));
            iabService.addIab(new Iab ( 349, 338, "Contemporary Hits/Pop/Top 40", "Music", "Contemporary Hits/Pop/Top 40", " ", " " ));
            iabService.addIab(new Iab ( 350, 338, "Country Music", "Music", "Country Music", " ", " " ));
            iabService.addIab(new Iab ( 351, 338, "Dance and Electronic Music", "Music", "Dance and Electronic Music", " ", " " ));
            iabService.addIab(new Iab ( 354, 338, "Gospel Music", "Music", "Gospel Music", " ", " " ));
            iabService.addIab(new Iab ( 355, 338, "Hip Hop Music", "Music", "Hip Hop Music", " ", " " ));
            iabService.addIab(new Iab ( 356, 338, "Inspirational/New Age Music", "Music", "Inspirational/New Age Music", " ", " " ));
            iabService.addIab(new Iab ( 357, 338, "Jazz", "Music", "Jazz", " ", " " ));
            iabService.addIab(new Iab ( 358, 338, "Oldies/Adult Standards", "Music", "Oldies/Adult Standards", " ", " " ));
            iabService.addIab(new Iab ( 362, 338, "R&B/Soul/Funk", "Music", "R&B/Soul/Funk", " ", " " ));
            iabService.addIab(new Iab ( 359, 338, "Reggae", "Music", "Reggae", " ", " " ));
            iabService.addIab(new Iab ( 361, 338, "Religious (Music and Audio)", "Music", "Religious (Music and Audio)", " ", " " ));
            iabService.addIab(new Iab ( 363, 338, "Rock Music", "Music", "Rock Music", " ", " " ));
            iabService.addIab(new Iab ( 364, 363, "Album-oriented Rock", "Music", "Rock Music", "Album-oriented Rock", " " ));
            iabService.addIab(new Iab ( 365, 363, "Alternative Rock", "Music", "Rock Music", "Alternative Rock", " " ));
            iabService.addIab(new Iab ( 366, 363, "Classic Rock", "Music", "Rock Music", "Classic Rock", " " ));
            iabService.addIab(new Iab ( 367, 363, "Hard Rock", "Music", "Rock Music", "Hard Rock", " " ));
            iabService.addIab(new Iab ( 368, 363, "Soft Rock", "Music", "Rock Music", "Soft Rock", " " ));
            iabService.addIab(new Iab ( 353, 338, "Songwriters/Folk", "Music", "Songwriters/Folk", " ", " " ));
            iabService.addIab(new Iab ( 369, 338, "Soundtracks, TV and Showtunes", "Music", "Soundtracks, TV and Showtunes", " ", " " ));
            iabService.addIab(new Iab ( 352, 338, "World/International Music", "Music", "World/International Music", " ", " " ));
            iabService.addIab(new Iab ( 377, 338, "Urban Contemporary Music", "Music", "Urban Contemporary Music", " ", " " ));
            iabService.addIab(new Iab ( 378, 338, "Variety (Music and Audio)", "Music", "Variety (Music and Audio)", " ", " " ));
            iabService.addIab(new Iab ( 163, 163, "Personal Celebrations & Life Events", "Personal Celebrations & Life Events", " ", " ", " " ));
            iabService.addIab(new Iab ( 164, 163, "Anniversary", "Personal Celebrations & Life Events", "Anniversary", " ", " " ));
            iabService.addIab(new Iab ( 166, 163, "Baby Shower", "Personal Celebrations & Life Events", "Baby Shower", " ", " " ));
            iabService.addIab(new Iab ( 167, 163, "Bachelor Party", "Personal Celebrations & Life Events", "Bachelor Party", " ", " " ));
            iabService.addIab(new Iab ( 168, 163, "Bachelorette Party", "Personal Celebrations & Life Events", "Bachelorette Party", " ", " " ));
            iabService.addIab(new Iab ( 169, 163, "Birth", "Personal Celebrations & Life Events", "Birth", " ", " " ));
            iabService.addIab(new Iab ( 170, 163, "Birthday", "Personal Celebrations & Life Events", "Birthday", " ", " " ));
            iabService.addIab(new Iab ( 171, 163, "Funeral", "Personal Celebrations & Life Events", "Funeral", " ", " " ));
            iabService.addIab(new Iab ( 172, 163, "Graduation", "Personal Celebrations & Life Events", "Graduation", " ", " " ));
            iabService.addIab(new Iab ( 173, 163, "Prom", "Personal Celebrations & Life Events", "Prom", " ", " " ));
            iabService.addIab(new Iab ( 165, 163, "Wedding", "Personal Celebrations & Life Events", "Wedding", " ", " " ));
            iabService.addIab(new Iab ( 391, null, "Personal Finance", "Personal Finance", " ", " ", " " ));
            iabService.addIab(new Iab ( 392, 391, "Consumer Banking", "Personal Finance", "Consumer Banking", " ", " " ));
            iabService.addIab(new Iab ( 393, 391, "Financial Assistance", "Personal Finance", "Financial Assistance", " ", " " ));
            iabService.addIab(new Iab ( 394, 393, "Government Support and Welfare", "Personal Finance", "Financial Assistance", "Government Support and Welfare", " " ));
            iabService.addIab(new Iab ( 395, 393, "Student Financial Aid", "Personal Finance", "Financial Assistance", "Student Financial Aid", " " ));
            iabService.addIab(new Iab ( 396, 391, "Financial Planning", "Personal Finance", "Financial Planning", " ", " " ));
            iabService.addIab(new Iab ( 397, 391, "Frugal Living", "Personal Finance", "Frugal Living", " ", " " ));
            iabService.addIab(new Iab ( 417, 391, "Home Utilities", "Personal Finance", "Home Utilities", " ", " " ));
            iabService.addIab(new Iab ( 418, 417, "Gas and Electric", "Personal Finance", "Home Utilities", "Gas and Electric", " " ));
            iabService.addIab(new Iab ( 419, 417, "Internet Service Providers", "Personal Finance", "Home Utilities", "Internet Service Providers", " " ));
            iabService.addIab(new Iab ( 420, 417, "Phone Services", "Personal Finance", "Home Utilities", "Phone Services", " " ));
            iabService.addIab(new Iab ( 421, 417, "Water Services", "Personal Finance", "Home Utilities", "Water Services", " " ));
            iabService.addIab(new Iab ( 398, 391, "Insurance", "Personal Finance", "Insurance", " ", " " ));
            iabService.addIab(new Iab ( 399, 398, "Health Insurance", "Personal Finance", "Insurance", "Health Insurance", " " ));
            iabService.addIab(new Iab ( 400, 398, "Home Insurance", "Personal Finance", "Insurance", "Home Insurance", " " ));
            iabService.addIab(new Iab ( 401, 398, "Life Insurance", "Personal Finance", "Insurance", "Life Insurance", " " ));
            iabService.addIab(new Iab ( 402, 398, "Motor Insurance", "Personal Finance", "Insurance", "Motor Insurance", " " ));
            iabService.addIab(new Iab ( 403, 398, "Pet Insurance", "Personal Finance", "Insurance", "Pet Insurance", " " ));
            iabService.addIab(new Iab ( 404, 398, "Travel Insurance", "Personal Finance", "Insurance", "Travel Insurance", " " ));
            iabService.addIab(new Iab ( 405, 391, "Personal Debt", "Personal Finance", "Personal Debt", " ", " " ));
            iabService.addIab(new Iab ( 406, 405, "Credit Cards", "Personal Finance", "Personal Debt", "Credit Cards", " " ));
            iabService.addIab(new Iab ( 407, 405, "Home Financing", "Personal Finance", "Personal Debt", "Home Financing", " " ));
            iabService.addIab(new Iab ( 408, 405, "Personal Loans", "Personal Finance", "Personal Debt", "Personal Loans", " " ));
            iabService.addIab(new Iab ( 409, 405, "Student Loans", "Personal Finance", "Personal Debt", "Student Loans", " " ));
            iabService.addIab(new Iab ( 410, 391, "Personal Investing", "Personal Finance", "Personal Investing", " ", " " ));
            iabService.addIab(new Iab ( 411, 410, "Hedge Funds", "Personal Finance", "Personal Investing", "Hedge Funds", " " ));
            iabService.addIab(new Iab ( 412, 410, "Mutual Funds", "Personal Finance", "Personal Investing", "Mutual Funds", " " ));
            iabService.addIab(new Iab ( 413, 410, "Options", "Personal Finance", "Personal Investing", "Options", " " ));
            iabService.addIab(new Iab ( 414, 410, "Stocks and Bonds", "Personal Finance", "Personal Investing", "Stocks and Bonds", " " ));
            iabService.addIab(new Iab ( 415, 391, "Personal Taxes", "Personal Finance", "Personal Taxes", " ", " " ));
            iabService.addIab(new Iab ( 416, 391, "Retirement Planning", "Personal Finance", "Retirement Planning", " ", " " ));
            iabService.addIab(new Iab ( 422, null, "Pets", "Pets", " ", " ", " " ));
            iabService.addIab(new Iab ( 423, 422, "Birds", "Pets", "Birds", " ", " " ));
            iabService.addIab(new Iab ( 424, 422, "Cats", "Pets", "Cats", " ", " " ));
            iabService.addIab(new Iab ( 425, 422, "Dogs", "Pets", "Dogs", " ", " " ));
            iabService.addIab(new Iab ( 426, 422, "Fish and Aquariums", "Pets", "Fish and Aquariums", " ", " " ));
            iabService.addIab(new Iab ( 427, 422, "Large Animals", "Pets", "Large Animals", " ", " " ));
            iabService.addIab(new Iab ( 428, 422, "Pet Adoptions", "Pets", "Pet Adoptions", " ", " " ));
            iabService.addIab(new Iab ( 431, 422, "Pet Supplies", "Pets", "Pet Supplies", " ", " " ));
            iabService.addIab(new Iab ( 429, 422, "Reptiles", "Pets", "Reptiles", " ", " " ));
            iabService.addIab(new Iab ( 430, 422, "Veterinary Medicine", "Pets", "Veterinary Medicine", " ", " " ));
            iabService.addIab(new Iab ( 386, null, "Politics", "Politics", " ", " ", " " ));
            iabService.addIab(new Iab ( 10013, 386, "Civic affairs", "Politics", "Civic affairs", " ", " " ));
            iabService.addIab(new Iab ( 387, 386, "Elections", "Politics", "Elections", " ", " " ));
            iabService.addIab(new Iab ( 388, 386, "Political Issues & Policy", "Politics", "Political Issues & policy", " ", " " ));
            iabService.addIab(new Iab ( 432, null, "Pop Culture", "Pop Culture", " ", " ", " " ));
            iabService.addIab(new Iab ( 433, 432, "Celebrity Deaths", "Pop Culture", "Celebrity Deaths", " ", " " ));
            iabService.addIab(new Iab ( 434, 432, "Celebrity Families", "Pop Culture", "Celebrity Families", " ", " " ));
            iabService.addIab(new Iab ( 435, 432, "Celebrity Homes", "Pop Culture", "Celebrity Homes", " ", " " ));
            iabService.addIab(new Iab ( 436, 432, "Celebrity Pregnancy", "Pop Culture", "Celebrity Pregnancy", " ", " " ));
            iabService.addIab(new Iab ( 437, 432, "Celebrity Relationships", "Pop Culture", "Celebrity Relationships", " ", " " ));
            iabService.addIab(new Iab ( 438, 432, "Celebrity Scandal", "Pop Culture", "Celebrity Scandal", " ", " " ));
            iabService.addIab(new Iab ( 439, 432, "Celebrity Style", "Pop Culture", "Celebrity Style", " ", " " ));
            iabService.addIab(new Iab ( 440, 432, "Humor and Satire", "Pop Culture", "Humor and Satire", " ", " " ));
            iabService.addIab(new Iab ( 10014, 602, "Productivity", "Productivity", " ", " ", " " ));
            iabService.addIab(new Iab ( 441, null, "Real Estate", "Real Estate", " ", " ", " " ));
            iabService.addIab(new Iab ( 442, 441, "Apartments", "Real Estate", "Apartments", " ", " " ));
            iabService.addIab(new Iab ( 445, 441, "Developmental Sites", "Real Estate", "Developmental Sites", " ", " " ));
            iabService.addIab(new Iab ( 446, 441, "Hotel Properties", "Real Estate", "Hotel Properties", " ", " " ));
            iabService.addIab(new Iab ( 447, 441, "Houses", "Real Estate", "Houses", " ", " " ));
            iabService.addIab(new Iab ( 448, 441, "Industrial Property", "Real Estate", "Industrial Property", " ", " " ));
            iabService.addIab(new Iab ( 449, 441, "Land and Farms", "Real Estate", "Land and Farms", " ", " " ));
            iabService.addIab(new Iab ( 450, 441, "Office Property", "Real Estate", "Office Property", " ", " " ));
            iabService.addIab(new Iab ( 451, 441, "Real Estate Buying and Selling", "Real Estate", "Real Estate Buying and Selling", " ", " " ));
            iabService.addIab(new Iab ( 452, 441, "Real Estate Renting and Leasing", "Real Estate", "Real Estate Renting and Leasing", " ", " " ));
            iabService.addIab(new Iab ( 443, 441, "Retail Property", "Real Estate", "Retail Property", " ", " " ));
            iabService.addIab(new Iab ( 444, 441, "Vacation Properties", "Real Estate", "Vacation Properties", " ", " " ));
            iabService.addIab(new Iab ( 453, null, "Religion & Spirituality", "Religion & Spirituality", " ", " ", " " ));
            iabService.addIab(new Iab ( 454, 453, "Agnosticism", "Religion & Spirituality", "Agnosticism", " ", " " ));
            iabService.addIab(new Iab ( 456, 453, "Astrology", "Religion & Spirituality", "Astrology", " ", " " ));
            iabService.addIab(new Iab ( 457, 453, "Atheism", "Religion & Spirituality", "Atheism", " ", " " ));
            iabService.addIab(new Iab ( 458, 453, "Buddhism", "Religion & Spirituality", "Buddhism", " ", " " ));
            iabService.addIab(new Iab ( 459, 453, "Christianity", "Religion & Spirituality", "Christianity", " ", " " ));
            iabService.addIab(new Iab ( 460, 453, "Hinduism", "Religion & Spirituality", "Hinduism", " ", " " ));
            iabService.addIab(new Iab ( 461, 453, "Islam", "Religion & Spirituality", "Islam", " ", " " ));
            iabService.addIab(new Iab ( 462, 453, "Judaism", "Religion & Spirituality", "Judaism", " ", " " ));
            iabService.addIab(new Iab ( 463, 453, "Sikhism", "Religion & Spirituality", "Sikhism", " ", " " ));
            iabService.addIab(new Iab ( 455, 453, "Spirituality", "Religion & Spirituality", "Spirituality", " ", " " ));
            iabService.addIab(new Iab ( 464, null, "Science", "Science", " ", " ", " " ));
            iabService.addIab(new Iab ( 465, 464, "Biological Sciences", "Science", "Biological Sciences", " ", " " ));
            iabService.addIab(new Iab ( 466, 464, "Chemistry", "Science", "Chemistry", " ", " " ));
            iabService.addIab(new Iab ( 467, 464, "Environment", "Science", "Environment", " ", " " ));
            iabService.addIab(new Iab ( 468, 464, "Genetics", "Science", "Genetics", " ", " " ));
            iabService.addIab(new Iab ( 469, 464, "Geography", "Science", "Geography", " ", " " ));
            iabService.addIab(new Iab ( 470, 464, "Geology", "Science", "Geology", " ", " " ));
            iabService.addIab(new Iab ( 471, 464, "Physics", "Science", "Physics", " ", " " ));
            iabService.addIab(new Iab ( 472, 464, "Space and Astronomy", "Science", "Space and Astronomy", " ", " " ));
            iabService.addIab(new Iab ( 390, 464, "Weather", "Science", "Weather", " ", " " ));
            iabService.addIab(new Iab ( 10015, null, "Sensitive Topics", "Sensitive Topics", " ", " ", " " ));
            iabService.addIab(new Iab ( 10016, 10015, "Adult & Explicit Sexual Content", "Sensitive Topics", "Adult & Explicit Sexual Content", " ", " " ));
            iabService.addIab(new Iab ( 10017, 10015, "Arms & Ammunition", "Sensitive Topics", "Arms & Ammunition", " ", " " ));
            iabService.addIab(new Iab ( 10018, 10015, "Crime & Harmful Acts to Individuals, Society & Human Right Violations", "Sensitive Topics", "Crime & Harmful Acts to Individuals, Society & Human Right Violations", " ", " " ));
            iabService.addIab(new Iab ( 10019, 10015, "Death, Injury, or Military Conflict", "Sensitive Topics", "Death, Injury, or Military Conflict", " ", " " ));
            iabService.addIab(new Iab ( 10020, 10015, "Debated Sensitive Social Issues", "Sensitive Topics", "Debated Sensitive Social Issues", " ", " " ));
            iabService.addIab(new Iab ( 10021, 10015, "Hate Speech and Acts of Aggression", "Sensitive Topics", "Hate Speech and Acts of Aggression", " ", " " ));
            iabService.addIab(new Iab ( 10047, 10015, "Illegal Drugs, Tobacco, eCigarettes, Vaping, Alcohol", "Sensitive Topics", "Illegal Drugs, Tobacco, eCigarettes, Vaping, Alcohol", " ", " " ));
            iabService.addIab(new Iab ( 10022, 10015, "Obscenity and Profanity", "Sensitive Topics", "Obscenity and Profanity", " ", " " ));
            iabService.addIab(new Iab ( 10023, 10015, "Online Piracy ", "Sensitive Topics", "Online Piracy ", " ", " " ));
            iabService.addIab(new Iab ( 10024, 10015, "Spam or Harmful Content", "Sensitive Topics", "Spam or Harmful Content", " ", " " ));
            iabService.addIab(new Iab ( 10025, 10015, "Terrorism", "Sensitive Topics", "Terrorism", " ", " " ));
            iabService.addIab(new Iab ( 473, null, "Shopping", "Shopping", " ", " ", " " ));
            iabService.addIab(new Iab ( 482, 473, "Children's Games and Toys", "Shopping", "Children's Games and Toys", " ", " " ));
            iabService.addIab(new Iab ( 474, 473, "Coupons and Discounts", "Shopping", "Coupons and Discounts", " ", " " ));
            iabService.addIab(new Iab ( 475, 473, "Flower Shopping", "Shopping", "Flower Shopping", " ", " " ));
            iabService.addIab(new Iab ( 476, 473, "Gifts and Greetings Cards", "Shopping", "Gifts and Greetings Cards", " ", " " ));
            iabService.addIab(new Iab ( 477, 473, "Grocery Shopping", "Shopping", "Grocery Shopping", " ", " " ));
            iabService.addIab(new Iab ( 478, 473, "Holiday Shopping", "Shopping", "Holiday Shopping", " ", " " ));
            iabService.addIab(new Iab ( 479, 473, "Household Supplies", "Shopping", "Household Supplies", " ", " " ));
            iabService.addIab(new Iab ( 480, 473, "Lotteries and Scratchcards", "Shopping", "Lotteries and Scratchcards", " ", " " ));
            iabService.addIab(new Iab ( 161, 473, "Party Supplies and Decorations", "Shopping", "Party Supplies and Decorations", " ", " " ));
            iabService.addIab(new Iab ( 481, 473, "Sales and Promotions", "Shopping", "Sales and Promotions", " ", " " ));
            iabService.addIab(new Iab ( 483, null, "Sports", "Sports", " ", " ", " " ));
            iabService.addIab(new Iab ( 484, 483, "American Football", "Sports", "American Football", " ", " " ));
            iabService.addIab(new Iab ( 507, 483, "Australian Rules Football", "Sports", "Australian Rules Football", " ", " " ));
            iabService.addIab(new Iab ( 518, 483, "Auto Racing", "Sports", "Auto Racing", " ", " " ));
            iabService.addIab(new Iab ( 519, 518, "Motorcycle Sports", "Sports", "Auto Racing", "Motorcycle Sports", " " ));
            iabService.addIab(new Iab ( 534, 483, "Badminton", "Sports", "Badminton", " ", " " ));
            iabService.addIab(new Iab ( 545, 483, "Baseball", "Sports", "Baseball", " ", " " ));
            iabService.addIab(new Iab ( 547, 483, "Basketball", "Sports", "Basketball", " ", " " ));
            iabService.addIab(new Iab ( 548, 483, "Beach Volleyball", "Sports", "Beach Volleyball", " ", " " ));
            iabService.addIab(new Iab ( 549, 483, "Bodybuilding", "Sports", "Bodybuilding", " ", " " ));
            iabService.addIab(new Iab ( 550, 483, "Bowling", "Sports", "Bowling", " ", " " ));
            iabService.addIab(new Iab ( 485, 483, "Boxing", "Sports", "Boxing", " ", " " ));
            iabService.addIab(new Iab ( 486, 483, "Cheerleading", "Sports", "Cheerleading", " ", " " ));
            iabService.addIab(new Iab ( 487, 483, "College Sports", "Sports", "College Sports", " ", " " ));
            iabService.addIab(new Iab ( 490, 487, "College Baseball", "Sports", "College Sports", "College Baseball", " " ));
            iabService.addIab(new Iab ( 489, 487, "College Basketball", "Sports", "College Sports", "College Basketball", " " ));
            iabService.addIab(new Iab ( 488, 487, "College Football", "Sports", "College Sports", "College Football", " " ));
            iabService.addIab(new Iab ( 491, 483, "Cricket", "Sports", "Cricket", " ", " " ));
            iabService.addIab(new Iab ( 492, 483, "Cycling", "Sports", "Cycling", " ", " " ));
            iabService.addIab(new Iab ( 493, 483, "Darts", "Sports", "Darts", " ", " " ));
            iabService.addIab(new Iab ( 494, 483, "Disabled Sports", "Sports", "Disabled Sports", " ", " " ));
            iabService.addIab(new Iab ( 495, 483, "Diving", "Sports", "Diving", " ", " " ));
            iabService.addIab(new Iab ( 496, 483, "Equine Sports", "Sports", "Equine Sports", " ", " " ));
            iabService.addIab(new Iab ( 497, 483, "Horse Racing", "Sports", "Equine Sports", "Horse Racing", " " ));
            iabService.addIab(new Iab ( 498, 483, "Extreme Sports", "Sports", "Extreme Sports", " ", " " ));
            iabService.addIab(new Iab ( 499, 498, "Canoeing and Kayaking", "Sports", "Extreme Sports", "Canoeing and Kayaking", " " ));
            iabService.addIab(new Iab ( 500, 498, "Climbing", "Sports", "Extreme Sports", "Climbing", " " ));
            iabService.addIab(new Iab ( 501, 498, "Paintball", "Sports", "Extreme Sports", "Paintball", " " ));
            iabService.addIab(new Iab ( 502, 498, "Scuba Diving", "Sports", "Extreme Sports", "Scuba Diving", " " ));
            iabService.addIab(new Iab ( 503, 498, "Skateboarding", "Sports", "Extreme Sports", "Skateboarding", " " ));
            iabService.addIab(new Iab ( 504, 498, "Snowboarding", "Sports", "Extreme Sports", "Snowboarding", " " ));
            iabService.addIab(new Iab ( 505, 498, "Surfing and Bodyboarding", "Sports", "Extreme Sports", "Surfing and Bodyboarding", " " ));
            iabService.addIab(new Iab ( 506, 498, "Waterskiing and Wakeboarding", "Sports", "Extreme Sports", "Waterskiing and Wakeboarding", " " ));
            iabService.addIab(new Iab ( 508, 483, "Fantasy Sports", "Sports", "Fantasy Sports", " ", " " ));
            iabService.addIab(new Iab ( 509, 483, "Field Hockey", "Sports", "Field Hockey", " ", " " ));
            iabService.addIab(new Iab ( 510, 483, "Figure Skating", "Sports", "Figure Skating", " ", " " ));
            iabService.addIab(new Iab ( 511, 483, "Fishing Sports", "Sports", "Fishing Sports", " ", " " ));
            iabService.addIab(new Iab ( 512, 483, "Golf", "Sports", "Golf", " ", " " ));
            iabService.addIab(new Iab ( 513, 483, "Gymnastics", "Sports", "Gymnastics", " ", " " ));
            iabService.addIab(new Iab ( 514, 483, "Hunting and Shooting", "Sports", "Hunting and Shooting", " ", " " ));
            iabService.addIab(new Iab ( 515, 483, "Ice Hockey", "Sports", "Ice Hockey", " ", " " ));
            iabService.addIab(new Iab ( 516, 483, "Inline Skating", "Sports", "Inline Skating", " ", " " ));
            iabService.addIab(new Iab ( 517, 483, "Lacrosse", "Sports", "Lacrosse", " ", " " ));
            iabService.addIab(new Iab ( 520, 483, "Martial Arts", "Sports", "Martial Arts", " ", " " ));
            iabService.addIab(new Iab ( 521, 483, "Olympic Sports", "Sports", "Olympic Sports", " ", " " ));
            iabService.addIab(new Iab ( 522, 521, "Summer Olympic Sports", "Sports", "Olympic Sports", "Summer Olympic Sports", " " ));
            iabService.addIab(new Iab ( 523, 521, "Winter Olympic Sports", "Sports", "Olympic Sports", "Winter Olympic Sports", " " ));
            iabService.addIab(new Iab ( 524, 483, "Poker and Professional Gambling", "Sports", "Poker and Professional Gambling", " ", " " ));
            iabService.addIab(new Iab ( 525, 483, "Rodeo", "Sports", "Rodeo", " ", " " ));
            iabService.addIab(new Iab ( 526, 483, "Rowing", "Sports", "Rowing", " ", " " ));
            iabService.addIab(new Iab ( 527, 483, "Rugby", "Sports", "Rugby", " ", " " ));
            iabService.addIab(new Iab ( 528, 527, "Rugby League", "Sports", "Rugby", "Rugby League", " " ));
            iabService.addIab(new Iab ( 529, 527, "Rugby Union", "Sports", "Rugby", "Rugby Union", " " ));
            iabService.addIab(new Iab ( 530, 483, "Sailing", "Sports", "Sailing", " ", " " ));
            iabService.addIab(new Iab ( 531, 483, "Skiing", "Sports", "Skiing", " ", " " ));
            iabService.addIab(new Iab ( 532, 483, "Snooker/Pool/Billiards", "Sports", "Snooker/Pool/Billiards", " ", " " ));
            iabService.addIab(new Iab ( 533, 483, "Soccer", "Sports", "Soccer", " ", " " ));
            iabService.addIab(new Iab ( 535, 483, "Softball", "Sports", "Softball", " ", " " ));
            iabService.addIab(new Iab ( 551, 483, "Sports Equipment", "Sports", "Sports Equipment", " ", " " ));
            iabService.addIab(new Iab ( 536, 483, "Squash", "Sports", "Squash", " ", " " ));
            iabService.addIab(new Iab ( 537, 483, "Swimming", "Sports", "Swimming", " ", " " ));
            iabService.addIab(new Iab ( 538, 483, "Table Tennis", "Sports", "Table Tennis", " ", " " ));
            iabService.addIab(new Iab ( 539, 483, "Tennis", "Sports", "Tennis", " ", " " ));
            iabService.addIab(new Iab ( 540, 483, "Track and Field", "Sports", "Track and Field", " ", " " ));
            iabService.addIab(new Iab ( 541, 483, "Volleyball", "Sports", "Volleyball", " ", " " ));
            iabService.addIab(new Iab ( 542, 483, "Walking", "Sports", "Walking", " ", " " ));
            iabService.addIab(new Iab ( 543, 483, "Water Polo", "Sports", "Water Polo", " ", " " ));
            iabService.addIab(new Iab ( 544, 483, "Weightlifting", "Sports", "Weightlifting", " ", " " ));
            iabService.addIab(new Iab ( 546, 483, "Wrestling", "Sports", "Wrestling", " ", " " ));
            iabService.addIab(new Iab ( 552, null, "Style & Fashion", "Style & Fashion", " ", " ", " " ));
            iabService.addIab(new Iab ( 553, 552, "Beauty", "Style & Fashion", "Beauty", " ", " " ));
            iabService.addIab(new Iab ( 554, 553, "Hair Care", "Style & Fashion", "Beauty", "Hair Care", " " ));
            iabService.addIab(new Iab ( 555, 553, "Makeup and Accessories", "Style & Fashion", "Beauty", "Makeup and Accessories", " " ));
            iabService.addIab(new Iab ( 556, 553, "Nail Care", "Style & Fashion", "Beauty", "Nail Care", " " ));
            iabService.addIab(new Iab ( 557, 553, "Natural and Organic Beauty", "Style & Fashion", "Beauty", "Natural and Organic Beauty", " " ));
            iabService.addIab(new Iab ( 558, 553, "Perfume and Fragrance", "Style & Fashion", "Beauty", "Perfume and Fragrance", " " ));
            iabService.addIab(new Iab ( 559, 553, "Skin Care", "Style & Fashion", "Beauty", "Skin Care", " " ));
            iabService.addIab(new Iab ( 574, 552, "Body Art", "Style & Fashion", "Body Art", " ", " " ));
            iabService.addIab(new Iab ( 575, 552, "Children's Clothing", "Style & Fashion", "Children's Clothing", " ", " " ));
            iabService.addIab(new Iab ( 576, 552, "Designer Clothing", "Style & Fashion", "Designer Clothing", " ", " " ));
            iabService.addIab(new Iab ( 577, 552, "Fashion Trends", "Style & Fashion", "Fashion Trends", " ", " " ));
            iabService.addIab(new Iab ( 578, 552, "High Fashion", "Style & Fashion", "High Fashion", " ", " " ));
            iabService.addIab(new Iab ( 579, 552, "Men's Fashion", "Style & Fashion", "Men's Fashion", " ", " " ));
            iabService.addIab(new Iab ( 580, 579, "Men's Accessories", "Style & Fashion", "Men's Fashion", "Men's Accessories", " " ));
            iabService.addIab(new Iab ( 581, 580, "Men's Jewelry and Watches", "Style & Fashion", "Men's Fashion", "Men's Accessories", "Men's Jewelry and Watches" ));
            iabService.addIab(new Iab ( 582, 579, "Men's Clothing", "Style & Fashion", "Men's Fashion", "Men's Clothing", " " ));
            iabService.addIab(new Iab ( 583, 582, "Men's Business Wear", "Style & Fashion", "Men's Fashion", "Men's Clothing", "Men's Business Wear" ));
            iabService.addIab(new Iab ( 584, 582, "Men's Casual Wear", "Style & Fashion", "Men's Fashion", "Men's Clothing", "Men's Casual Wear" ));
            iabService.addIab(new Iab ( 585, 582, "Men's Formal Wear", "Style & Fashion", "Men's Fashion", "Men's Clothing", "Men's Formal Wear" ));
            iabService.addIab(new Iab ( 586, 582, "Men's Outerwear", "Style & Fashion", "Men's Fashion", "Men's Clothing", "Men's Outerwear" ));
            iabService.addIab(new Iab ( 587, 582, "Men's Sportswear", "Style & Fashion", "Men's Fashion", "Men's Clothing", "Men's Sportswear" ));
            iabService.addIab(new Iab ( 588, 582, "Men's Underwear and Sleepwear", "Style & Fashion", "Men's Fashion", "Men's Clothing", "Men's Underwear and Sleepwear" ));
            iabService.addIab(new Iab ( 589, 579, "Men's Shoes and Footwear", "Style & Fashion", "Men's Fashion", "Men's Shoes and Footwear", " " ));
            iabService.addIab(new Iab ( 590, 552, "Personal Care", "Style & Fashion", "Personal Care", " ", " " ));
            iabService.addIab(new Iab ( 591, 590, "Bath and Shower", "Style & Fashion", "Personal Care", "Bath and Shower", " " ));
            iabService.addIab(new Iab ( 592, 590, "Deodorant and Antiperspirant", "Style & Fashion", "Personal Care", "Deodorant and Antiperspirant", " " ));
            iabService.addIab(new Iab ( 593, 590, "Oral care", "Style & Fashion", "Personal Care", "Oral care", " " ));
            iabService.addIab(new Iab ( 594, 590, "Shaving", "Style & Fashion", "Personal Care", "Shaving", " " ));
            iabService.addIab(new Iab ( 595, 552, "Street Style", "Style & Fashion", "Street Style", " ", " " ));
            iabService.addIab(new Iab ( 560, 552, "Women's Fashion", "Style & Fashion", "Women's Fashion", " ", " " ));
            iabService.addIab(new Iab ( 561, 560, "Women's Accessories", "Style & Fashion", "Women's Fashion", "Women's Accessories", " " ));
            iabService.addIab(new Iab ( 562, 561, "Women's Glasses", "Style & Fashion", "Women's Fashion", "Women's Accessories", "Women's Glasses" ));
            iabService.addIab(new Iab ( 563, 561, "Women's Handbags and Wallets", "Style & Fashion", "Women's Fashion", "Women's Accessories", "Women's Handbags and Wallets" ));
            iabService.addIab(new Iab ( 564, 561, "Women's Hats and Scarves", "Style & Fashion", "Women's Fashion", "Women's Accessories", "Women's Hats and Scarves" ));
            iabService.addIab(new Iab ( 565, 561, "Women's Jewelry and Watches", "Style & Fashion", "Women's Fashion", "Women's Accessories", "Women's Jewelry and Watches" ));
            iabService.addIab(new Iab ( 566, 560, "Women's Clothing", "Style & Fashion", "Women's Fashion", "Women's Clothing", " " ));
            iabService.addIab(new Iab ( 567, 566, "Women's Business Wear", "Style & Fashion", "Women's Fashion", "Women's Clothing", "Women's Business Wear" ));
            iabService.addIab(new Iab ( 568, 566, "Women's Casual Wear", "Style & Fashion", "Women's Fashion", "Women's Clothing", "Women's Casual Wear" ));
            iabService.addIab(new Iab ( 569, 566, "Women's Formal Wear", "Style & Fashion", "Women's Fashion", "Women's Clothing", "Women's Formal Wear" ));
            iabService.addIab(new Iab ( 570, 566, "Women's Intimates and Sleepwear", "Style & Fashion", "Women's Fashion", "Women's Clothing", "Women's Intimates and Sleepwear" ));
            iabService.addIab(new Iab ( 571, 566, "Women's Outerwear", "Style & Fashion", "Women's Fashion", "Women's Clothing", "Women's Outerwear" ));
            iabService.addIab(new Iab ( 572, 566, "Women's Sportswear", "Style & Fashion", "Women's Fashion", "Women's Clothing", "Women's Sportswear" ));
            iabService.addIab(new Iab ( 573, 560, "Women's Shoes and Footwear", "Style & Fashion", "Women's Fashion", "Women's Shoes and Footwear", " " ));
            iabService.addIab(new Iab ( 596, null, "Technology & Computing", "Technology & Computing", " ", " ", " " ));
            iabService.addIab(new Iab ( 597, 596, "Artificial Intelligence", "Technology & Computing", "Artificial Intelligence", " ", " " ));
            iabService.addIab(new Iab ( 598, 596, "Augmented Reality", "Technology & Computing", "Augmented Reality", " ", " " ));
            iabService.addIab(new Iab ( 599, 596, "Computing", "Technology & Computing", "Computing", " ", " " ));
            iabService.addIab(new Iab ( 600, 599, "Computer Networking", "Technology & Computing", "Computing", "Computer Networking", " " ));
            iabService.addIab(new Iab ( 601, 599, "Computer Peripherals", "Technology & Computing", "Computing", "Computer Peripherals", " " ));
            iabService.addIab(new Iab ( 602, 599, "Software and Applications", "Technology & Computing", "Computing", "Computer Software and Applications", " " ));
            iabService.addIab(new Iab ( 603, 602, "3-D Graphics", "Technology & Computing", "Computing", "Computer Software and Applications", "3-D Graphics" ));
            iabService.addIab(new Iab ( 608, 602, "Antivirus Software", "Technology & Computing", "Computing", "Computer Software and Applications", "Antivirus Software" ));
            iabService.addIab(new Iab ( 609, 602, "Browsers", "Technology & Computing", "Computing", "Computer Software and Applications", "Browsers" ));
            iabService.addIab(new Iab ( 610, 602, "Computer Animation", "Technology & Computing", "Computing", "Computer Software and Applications", "Computer Animation" ));
            iabService.addIab(new Iab ( 611, 602, "Databases", "Technology & Computing", "Computing", "Computer Software and Applications", "Databases" ));
            iabService.addIab(new Iab ( 612, 602, "Desktop Publishing", "Technology & Computing", "Computing", "Computer Software and Applications", "Desktop Publishing" ));
            iabService.addIab(new Iab ( 613, 602, "Digital Audio", "Technology & Computing", "Computing", "Computer Software and Applications", "Digital Audio" ));
            iabService.addIab(new Iab ( 614, 602, "Graphics Software", "Technology & Computing", "Computing", "Computer Software and Applications", "Graphics Software" ));
            iabService.addIab(new Iab ( 615, 602, "Operating Systems", "Technology & Computing", "Computing", "Computer Software and Applications", "Operating Systems" ));
            iabService.addIab(new Iab ( 604, 602, "Photo Editing Software", "Technology & Computing", "Computing", "Computer Software and Applications", "Photo Editing Software" ));
            iabService.addIab(new Iab ( 605, 602, "Shareware and Freeware", "Technology & Computing", "Computing", "Computer Software and Applications", "Shareware and Freeware" ));
            iabService.addIab(new Iab ( 606, 602, "Video Software", "Technology & Computing", "Computing", "Computer Software and Applications", "Video Software" ));
            iabService.addIab(new Iab ( 607, 602, "Web Conferencing", "Technology & Computing", "Computing", "Computer Software and Applications", "Web Conferencing" ));
            iabService.addIab(new Iab ( 616, 599, "Data Storage and Warehousing", "Technology & Computing", "Computing", "Data Storage and Warehousing", " " ));
            iabService.addIab(new Iab ( 617, 599, "Desktops", "Technology & Computing", "Computing", "Desktops", " " ));
            iabService.addIab(new Iab ( 618, 599, "Information and Network Security", "Technology & Computing", "Computing", "Information and Network Security", " " ));
            iabService.addIab(new Iab ( 619, 599, "Internet", "Technology & Computing", "Computing", "Internet", " " ));
            iabService.addIab(new Iab ( 620, 619, "Cloud Computing", "Technology & Computing", "Computing", "Internet", "Cloud Computing" ));
            iabService.addIab(new Iab ( 623, 619, "Email", "Technology & Computing", "Computing", "Internet", "Email" ));
            iabService.addIab(new Iab ( 624, 619, "Internet for Beginners", "Technology & Computing", "Computing", "Internet", "Internet for Beginners" ));
            iabService.addIab(new Iab ( 625, 619, "Internet of Things", "Technology & Computing", "Computing", "Internet", "Internet of Things" ));
            iabService.addIab(new Iab ( 626, 619, "IT and Internet Support", "Technology & Computing", "Computing", "Internet", "IT and Internet Support" ));
            iabService.addIab(new Iab ( 627, 619, "Search", "Technology & Computing", "Computing", "Internet", "Search" ));
            iabService.addIab(new Iab ( 628, 619, "Social Networking", "Technology & Computing", "Computing", "Internet", "Social Networking" ));
            iabService.addIab(new Iab ( 629, 619, "Web Design and HTML", "Technology & Computing", "Computing", "Internet", "Web Design and HTML" ));
            iabService.addIab(new Iab ( 621, 619, "Web Development", "Technology & Computing", "Computing", "Internet", "Web Development" ));
            iabService.addIab(new Iab ( 622, 619, "Web Hosting", "Technology & Computing", "Computing", "Internet", "Web Hosting" ));
            iabService.addIab(new Iab ( 630, 599, "Laptops", "Technology & Computing", "Computing", "Laptops", " " ));
            iabService.addIab(new Iab ( 631, 599, "Programming Languages", "Technology & Computing", "Computing", "Programming Languages", " " ));
            iabService.addIab(new Iab ( 632, 596, "Consumer Electronics", "Technology & Computing", "Consumer Electronics", " ", " " ));
            iabService.addIab(new Iab ( 633, 632, "Cameras and Camcorders", "Technology & Computing", "Consumer Electronics", "Cameras and Camcorders", " " ));
            iabService.addIab(new Iab ( 634, 632, "Home Entertainment Systems", "Technology & Computing", "Consumer Electronics", "Home Entertainment Systems", " " ));
            iabService.addIab(new Iab ( 635, 632, "Smartphones", "Technology & Computing", "Consumer Electronics", "Smartphones", " " ));
            iabService.addIab(new Iab ( 636, 632, "Tablets and E-readers", "Technology & Computing", "Consumer Electronics", "Tablets and E-readers", " " ));
            iabService.addIab(new Iab ( 637, 632, "Wearable Technology", "Technology & Computing", "Consumer Electronics", "Wearable Technology", " " ));
            iabService.addIab(new Iab ( 638, 596, "Robotics", "Technology & Computing", "Robotics", " ", " " ));
            iabService.addIab(new Iab ( 639, 596, "Virtual Reality", "Technology & Computing", "Virtual Reality", " ", " " ));
            iabService.addIab(new Iab ( 653, null, "Travel", "Travel", " ", " ", " " ));
            iabService.addIab(new Iab ( 654, 653, "Travel Accessories", "Travel", "Travel Accessories", " ", " " ));
            iabService.addIab(new Iab ( 655, 653, "Travel Locations", "Travel", "Travel Locations", " ", " " ));
            iabService.addIab(new Iab ( 656, 655, "Africa Travel", "Travel", "Travel Locations", "Africa Travel", " " ));
            iabService.addIab(new Iab ( 657, 655, "Asia Travel", "Travel", "Travel Locations", "Asia Travel", " " ));
            iabService.addIab(new Iab ( 658, 655, "Australia and Oceania Travel", "Travel", "Travel Locations", "Australia and Oceania Travel", " " ));
            iabService.addIab(new Iab ( 659, 655, "Europe Travel", "Travel", "Travel Locations", "Europe Travel", " " ));
            iabService.addIab(new Iab ( 660, 655, "North America Travel", "Travel", "Travel Locations", "North America Travel", " " ));
            iabService.addIab(new Iab ( 661, 655, "Polar Travel", "Travel", "Travel Locations", "Polar Travel", " " ));
            iabService.addIab(new Iab ( 662, 655, "South America Travel", "Travel", "Travel Locations", "South America Travel", " " ));
            iabService.addIab(new Iab ( 663, 653, "Travel Preparation and Advice", "Travel", "Travel Preparation and Advice", " ", " " ));
            iabService.addIab(new Iab ( 664, 653, "Travel Type", "Travel", "Travel Type", " ", " " ));
            iabService.addIab(new Iab ( 665, 664, "Adventure Travel", "Travel", "Travel Type", "Adventure Travel", " " ));
            iabService.addIab(new Iab ( 672, 664, "Air Travel", "Travel", "Travel Type", "Air Travel", " " ));
            iabService.addIab(new Iab ( 673, 664, "Beach Travel", "Travel", "Travel Type", "Beach Travel", " " ));
            iabService.addIab(new Iab ( 674, 664, "Bed & Breakfasts", "Travel", "Travel Type", "Bed & Breakfasts", " " ));
            iabService.addIab(new Iab ( 675, 664, "Budget Travel", "Travel", "Travel Type", "Budget Travel", " " ));
            iabService.addIab(new Iab ( 676, 664, "Business Travel", "Travel", "Travel Type", "Business Travel", " " ));
            iabService.addIab(new Iab ( 677, 664, "Camping", "Travel", "Travel Type", "Camping", " " ));
            iabService.addIab(new Iab ( 678, 664, "Cruises", "Travel", "Travel Type", "Cruises", " " ));
            iabService.addIab(new Iab ( 679, 664, "Day Trips", "Travel", "Travel Type", "Day Trips", " " ));
            iabService.addIab(new Iab ( 666, 664, "Family Travel", "Travel", "Travel Type", "Family Travel", " " ));
            iabService.addIab(new Iab ( 667, 664, "Honeymoons and Getaways", "Travel", "Travel Type", "Honeymoons and Getaways", " " ));
            iabService.addIab(new Iab ( 668, 664, "Hotels and Motels", "Travel", "Travel Type", "Hotels and Motels", " " ));
            iabService.addIab(new Iab ( 669, 664, "Rail Travel", "Travel", "Travel Type", "Rail Travel", " " ));
            iabService.addIab(new Iab ( 670, 664, "Road Trips", "Travel", "Travel Type", "Road Trips", " " ));
            iabService.addIab(new Iab ( 671, 664, "Spas", "Travel", "Travel Type", "Spas", " " ));
            iabService.addIab(new Iab ( 680, null, "Video Gaming", "Video Gaming", " ", " ", " " ));
            iabService.addIab(new Iab ( 681, 680, "Console Games", "Video Gaming", "Console Games", " ", " " ));
            iabService.addIab(new Iab ( 682, 680, "eSports", "Video Gaming", "eSports", " ", " " ));
            iabService.addIab(new Iab ( 683, 680, "Mobile Games", "Video Gaming", "Mobile Games", " ", " " ));
            iabService.addIab(new Iab ( 684, 680, "PC Games", "Video Gaming", "PC Games", " ", " " ));
            iabService.addIab(new Iab ( 685, 680, "Video Game Genres", "Video Gaming", "Video Game Genres", " ", " " ));
            iabService.addIab(new Iab ( 686, 685, "Action Video Games", "Video Gaming", "Video Game Genres", "Action Video Games", " " ));
            iabService.addIab(new Iab ( 691, 685, "Action-Adventure Video Games", "Video Gaming", "Video Game Genres", "Action-Adventure Video Games", " " ));
            iabService.addIab(new Iab ( 10026, 685, "Adult Video Games", "Video Gaming", "Video Game Genres", "Adult Video Games", " " ));
            iabService.addIab(new Iab ( 692, 685, "Adventure Video Games", "Video Gaming", "Video Game Genres", "Adventure Video Games", " " ));
            iabService.addIab(new Iab ( 10027, 685, "Casino and Gambling Video Games", "Video Gaming", "Video Game Genres", "Casino and Gambling Video Games", " " ));
            iabService.addIab(new Iab ( 693, 685, "Casual Games", "Video Gaming", "Video Game Genres", "Casual Games", " " ));
            iabService.addIab(new Iab ( 694, 685, "Educational Video Games", "Video Gaming", "Video Game Genres", "Educational Video Games", " " ));
            iabService.addIab(new Iab ( 695, 685, "Exercise and Fitness Video Games", "Video Gaming", "Video Game Genres", "Exercise and Fitness Video Games", " " ));
            iabService.addIab(new Iab ( 10028, 685, "Family Video Games", "Video Gaming", "Video Game Genres", "Family Video Games", " " ));
            iabService.addIab(new Iab ( 10029, 685, "Horror Video Games", "Video Gaming", "Video Game Genres", "Horror Video Games", " " ));
            iabService.addIab(new Iab ( 696, 685, "MMOs", "Video Gaming", "Video Game Genres", "MMOs", " " ));
            iabService.addIab(new Iab ( 697, 685, "Music and Party Video Games", "Video Gaming", "Video Game Genres", "Music and Party Video Games", " " ));
            iabService.addIab(new Iab ( 698, 685, "Puzzle Video Games", "Video Gaming", "Video Game Genres", "Puzzle Video Games", " " ));
            iabService.addIab(new Iab ( 10030, 685, "Racing Video Games", "Video Gaming", "Video Game Genres", "Racing Video Games", " " ));
            iabService.addIab(new Iab ( 687, 685, "Role-Playing Video Games", "Video Gaming", "Video Game Genres", "Role-Playing Video Games", " " ));
            iabService.addIab(new Iab ( 688, 685, "Simulation Video Games", "Video Gaming", "Video Game Genres", "Simulation Video Games", " " ));
            iabService.addIab(new Iab ( 689, 685, "Sports Video Games", "Video Gaming", "Video Game Genres", "Sports Video Games", " " ));
            iabService.addIab(new Iab ( 690, 685, "Strategy Video Games", "Video Gaming", "Video Game Genres", "Strategy Video Games", " " ));
            iabService.addIab(new Iab ( 389, null, "War and Conflicts", "War and Conflicts", " ", " ", " " ));
            iabService.addIab(new Iab ( 1000, null, "Content Environment", "Content Environment", "", "", "" ));
            iabService.addIab(new Iab ( 1002, 1000, "Email", "Content Environment", "Email", "", "" ));
            iabService.addIab(new Iab ( 1003, 1000, "Forum/Community", "Content Environment", "Forum/Community", "", "" ));
            iabService.addIab(new Iab ( 1005, 1000, "Marketplace/eCommerce", "Content Environment", "Marketplace/eCommerce", "", "" ));
            iabService.addIab(new Iab ( 1006, 1000, "Search Engine/Listings", "Content Environment", "Search Engine/Listings", "", "" ));
            iabService.addIab(new Iab ( 1007, 1000, "Social", "Content Environment", "Social", "", "" ));
            iabService.addIab(new Iab ( 1008, 1000, "Utility/Online Tool", "Content Environment", "Utility/Online Tool", "", "" ));
            iabService.addIab(new Iab ( 1009, 1000, "Voice Activated Channels", "Content Environment", "Voice Activated Channels", "", "" ));
            iabService.addIab(new Iab ( 10031, 1000, "General", "Content Environment", "General", "", "" ));
            iabService.addIab(new Iab ( 1010, null, "Content Purpose", "Content Purpose", "", "", "" ));
            iabService.addIab(new Iab ( 1012, 1010, "Conversational", "Content Purpose", "Conversational", "", "" ));
            iabService.addIab(new Iab ( 1014, 1010, "Entertainment Content", "Content Purpose", "Entertainment Content", "", "" ));
            iabService.addIab(new Iab ( 10032, 1010, "Informational", "Content Purpose", "Informational", "", "" ));
            iabService.addIab(new Iab ( 1011, 10032, "Academic/Research Content", "Content Purpose", "Informational", "Academic/ResearchConent", "" ));
            iabService.addIab(new Iab ( 1013, 10032, "Educational Content", "Content Purpose", "Informational", "Educational Content", "" ));
            iabService.addIab(new Iab ( 1017, 10032, "Instructional Content", "Content Purpose", "Informational", "Instructional Content", "" ));
            iabService.addIab(new Iab ( 1020, 10032, "News", "Content Purpose", "Informational", "News", "" ));
            iabService.addIab(new Iab ( 10033, 10032, "Opinion & Op-Ed", "Content Purpose", "Informational", "Opinions & Op-Eds", "" ));
            iabService.addIab(new Iab ( 1021, 10032, "Review", "Content Purpose", "Informational", "Review", "" ));
            iabService.addIab(new Iab ( 1019, 1010, "Commerce", "Content Purpose", "Commerce", "", "" ));
            iabService.addIab(new Iab ( 1215, null, "Content Source", "Content Source", "", "", "" ));
            iabService.addIab(new Iab ( 1216, 1215, "Professionally Produced", "Content Source", "Professionally Produced", "", "" ));
            iabService.addIab(new Iab ( 1217, 1215, "User Generated", "Content Source", "User Generated", "", "" ));
            iabService.addIab(new Iab ( 1218, 1215, "Aggregated/Curated", "Content Source", "Aggregated/Curated", "", "" ));
            iabService.addIab(new Iab ( 1022, null, "Content Form Factor", "Content Form Factor", "", "", "" ));
            iabService.addIab(new Iab ( 1023, 1022, "Audio", "Content Form Factor", "Audio", "", "" ));
            iabService.addIab(new Iab ( 10034, 1023, "Podcast", "Content Form Factor", "Audio", "Podcast", "" ));
            iabService.addIab(new Iab ( 10035, 1023, "Radio", "Content Form Factor", "Audio", "Radio", "" ));
            iabService.addIab(new Iab ( 10036, 1023, "Event", "Content Form Factor", "Audio", "Event", "" ));
            iabService.addIab(new Iab ( 1024, 1022, "Images/Galleries", "Content Form Factor", "Images/Galleries", "", "" ));
            iabService.addIab(new Iab ( 1026, 1022, "Mixed", "Content Form Factor", "Mixed", "", "" ));
            iabService.addIab(new Iab ( 1027, 1022, "Textual", "Content Form Factor", "Textual", "", "" ));
            iabService.addIab(new Iab ( 1028, 1022, "Video", "Content Form Factor", "Video", "", "" ));
            iabService.addIab(new Iab ( 10037, 1028, "Show", "Content Form Factor", "Video", "Show", "" ));
            iabService.addIab(new Iab ( 10038, 10037, "Episodic Show", "Content Form Factor", "Video", "Show", "Episodic Show" ));
            iabService.addIab(new Iab ( 10039, 1028, "Event", "Content Form Factor", "Video", "Event", "" ));
            iabService.addIab(new Iab ( 10040, 1028, "Clip", "Content Form Factor", "Video", "Clip", "" ));
            iabService.addIab(new Iab ( 10041, 1028, "Movie", "Content Form Factor", "Video", "Movie", "" ));
            iabService.addIab(new Iab ( 1004, 1022, "Game", "Content Form Factor", "Game", "", "" ));
            iabService.addIab(new Iab ( 1029, 1022, "VR/AR", "Content Form Factor", "VR/AR", "", "" ));
            iabService.addIab(new Iab ( 10042, null, "Brand Suitability and Risk", "Brand Suitability and Risk", "", "", "" ));
            iabService.addIab(new Iab ( 10043, 10042, "Floor", "Brand Suitability and Risk", "", "", "" ));
            iabService.addIab(new Iab ( 10044, 10042, "High Risk", "Brand Suitability and Risk", "", "", "" ));
            iabService.addIab(new Iab ( 10045, 10042, "Medium Risk", "Brand Suitability and Risk", "", "", "" ));
            iabService.addIab(new Iab ( 10046, 10042, "Low Risk", "Brand Suitability and Risk", "", "", "" ));
            iabService.addIab(new Iab ( 1030, null, "*Content Language Extension", "*Content Language Extension", "", "", "" ));

        } catch (Exception e) {
            System.err.println("❌ Error initializing sample iabs: " + e.getMessage());
        }
    }
}
