server:
  port: 8080

spring:
  application:
    name: mcp-server-rag-llm

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:rag-llm
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

    show-sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

  ai:
    mcp:
      server:
        enabled: true
        stdio: true
        name: mcp-server-rag-llm
        version: 1.0.0
        description: Example MCP Server with RAG LLM
        resourceChangeNotification : true
        toolChangeNotification : true
        promptChangeNotification: true
        sseEndpoint : /mcp/sse
        sseMessageEndpoint: /mcp/sse/message
        type: sync
        capabilities:
          completion: true
          prompt: true
          tool: true
          resource: true

    vectorstore.qdrant.host: localhost
    vectorstore.qdrant.port: 6334
    #vectorstore.qdrant.api-key=<your api key>
    vectorstore.qdrant.collection-name: my_iabs
    # Optional: automatically create the schema/collection if it doesn't exist
    vectorstore.qdrant.initialize-schema: true

    ollama:
      base-url: http://localhost:11434 #http://host.docker.internal:11434
      chat:
        options:
          model: phi3:mini
      embedding:
        enabled: true
        options:
          model: all-minilm:latest

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # for claude desktop
  main:
    banner-mode: off
    web-application-type: none


# Cache Configuration
cache:
  ttl: 3600  # 1 hour in seconds
  enabled: true





#dataFileName: iab.csv

logging:
  level:
    io.modelcontextprotocol: DEBUG
    org.springframework.ai.mcp: WARN
    root: WARN
    org.springframework: OFF
    org.hibernate: OFF
    com.zaxxer.hikari: OFF

  # for claude desktop
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
